import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Roman Numeral Converter - Free Number to Roman Numeral Converter | The Tutor Bridge',
  description: 'Free Roman numeral converter with bi-directional conversion. Convert numbers to Roman numerals (1-3999) and Roman numerals to numbers instantly. Step-by-step explanations and comprehensive Roman numeral guide.',
  keywords: [
    'roman numeral converter',
    'convert to roman numerals',
    'roman numerals converter',
    'number to roman numeral',
    'roman numeral to number',
    'roman numerals calculator',
    'roman numeral translator',
    'roman numeral generator',
    'how to convert to roman numerals',
    'roman numerals chart',
    'roman numerals 1-100',
    'roman numerals 1-1000',
    'roman numerals rules',
    'roman numeral system',
    'arabic to roman numerals',
    'roman to arabic numerals',
    'free roman numeral converter',
    'online roman numeral converter',
    'roman numeral converter with steps',
    'roman numerals to numbers',
    'numbers to roman numerals',
    'convert numbers to roman',
    'roman numeral conversion',
    'roman numeral decoder',
    'roman numeral encoder',
    'roman numerals meaning',
    'roman numerals explained',
    'learn roman numerals',
    'roman numeral conversion chart',
    'roman numeral symbols',
    'I II III IV V VI VII VIII IX X',
    'L C D M roman numerals',
    'roman numerals history',
    'roman numerals examples',
    'roman numerals practice',
    'roman numeral conversion calculator',
    'roman numeral tool',
    'roman numerals for students',
    'educational roman numeral converter',
    'roman numeral conversion rules',
    'subtractive notation roman numerals',
    'additive notation roman numerals',
    'roman numerals 2024',
    'current year in roman numerals',
    'age in roman numerals',
    'date in roman numerals',
    'roman numeral clock',
    'super bowl roman numerals',
    'movie roman numerals',
    'copyright roman numerals',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/roman-numeral-converter',
  },
  openGraph: {
    title: 'Roman Numeral Converter - Free Number Converter Tool',
    description: 'Convert numbers to Roman numerals and vice versa instantly. Bi-directional converter with step-by-step explanations for numbers 1-3999.',
    url: 'https://www.thetutorbridge.com/calculators/roman-numeral-converter',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Roman Numeral Converter - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Roman Numeral Converter - Free Conversion Tool',
    description: 'Convert between numbers and Roman numerals instantly with step-by-step explanations.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RomanNumeralConverterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
