import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SGPA to Percentage Calculator - Convert GPA to % Instantly | The Tutor Bridge',
  description: 'Free SGPA to percentage calculator with step-by-step conversion formulas. Convert semester GPA to percentage for CBSE, VTU, Anna University, and all Indian universities. Supports 4.0 and 10.0 scales with comprehensive examples.',
  keywords: [
    'sgpa to percentage calculator',
    'sgpa to percentage conversion',
    'calculate percentage from sgpa',
    'convert sgpa to percentage',
    'sgpa percentage calculator',
    'how to convert sgpa to percentage',
    'sgpa to marks percentage',
    'semester gpa to percentage',
    'gpa to percentage calculator',
    'sgpa percentage conversion formula',
    'free sgpa calculator',
    'online sgpa to percentage converter',
    'sgpa to percentage formula',
    'cbse sgpa to percentage',
    'vtu sgpa to percentage',
    'anna university sgpa to percentage',
    'jntu sgpa to percentage',
    'mumbai university sgpa to percentage',
    'iit sgpa to percentage',
    'nit sgpa to percentage',
    'engineering sgpa to percentage',
    '10 point sgpa to percentage',
    '4 point gpa to percentage',
    'sgpa percentage conversion table',
    'how to calculate percentage from sgpa',
    'sgpa marks calculator',
    'semester grade to percentage',
    'university gpa calculator',
    'academic percentage calculator',
    'sgpa to percentage cbse formula',
    'sgpa percentage converter online',
    'calculate marks from sgpa',
    'btech sgpa to percentage',
    'mtech sgpa to percentage',
    'bca sgpa to percentage',
    'mca sgpa to percentage',
    'mba sgpa to percentage',
    'be sgpa to percentage',
    'bcom sgpa to percentage',
    'bsc sgpa to percentage',
    'sgpa 8.5 to percentage',
    'sgpa 9 to percentage',
    'sgpa 7 to percentage',
    'what is sgpa percentage',
    'sgpa meaning and calculation',
    'gpa percentage conversion chart',
    'university grading system calculator',
    'semester marks calculator',
    'academic performance calculator',
    'grade point to percentage',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/sgpa-to-percentage-calculator',
  },
  openGraph: {
    title: 'SGPA to Percentage Calculator - Convert GPA to % Instantly',
    description: 'Free SGPA to percentage calculator with step-by-step conversion formulas. Convert semester GPA to percentage for all universities with comprehensive examples.',
    url: 'https://thetutorbridge.com/calculators/sgpa-to-percentage-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'SGPA to Percentage Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SGPA to Percentage Calculator - Convert GPA to % Instantly',
    description: 'Calculate percentage from SGPA with detailed step-by-step solutions and comprehensive conversion formulas for all universities.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function SGPAToPercentageCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
