import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Amortization Calculator - Free Loan Amortization Schedule Calculator | The Tutor Bridge',
  description: 'Free amortization calculator to create detailed loan amortization schedules. Calculate monthly payments, total interest, and principal breakdown with extra payment options.',
  keywords: [
    'amortization calculator',
    'loan amortization calculator',
    'amortization schedule calculator',
    'mortgage amortization calculator',
    'loan payment calculator',
    'amortization table calculator',
    'auto loan amortization calculator',
    'home loan amortization calculator',
    'calculate amortization schedule',
    'loan amortization schedule',
    'amortization formula',
    'amortization calculator with extra payments',
    'loan calculator with amortization schedule',
    'mortgage amortization schedule',
    'car loan amortization calculator',
    'personal loan amortization calculator',
    'loan amortization chart',
    'amortization calculator online',
    'free amortization calculator',
    'simple amortization calculator',
    'loan amortization table',
    'monthly amortization calculator',
    'yearly amortization calculator',
    'loan principal and interest calculator',
    'amortization schedule with extra payments',
    'early payoff calculator',
    'loan payoff calculator',
    'extra payment calculator',
    'accelerated loan payoff',
    'loan prepayment calculator',
    'amortization schedule excel',
    'loan amortization formula',
    'how to calculate amortization',
    'what is amortization',
    'amortization meaning',
    'amortization definition',
    'loan amortization explained',
    'amortization vs depreciation',
    'negative amortization',
    'straight line amortization',
    'declining balance amortization',
    'amortization period',
    'loan term calculator',
    'interest amortization',
    'principal amortization',
    'loan balance calculator',
    'remaining balance calculator',
    'loan interest calculator',
    'total interest paid calculator',
    'loan comparison calculator',
    'debt payoff calculator',
    'loan repayment calculator',
    'installment loan calculator',
    'fixed rate loan calculator',
    'amortization calculator with date',
    'loan start date calculator',
    'payment schedule calculator',
    'loan payoff schedule',
    'amortization breakdown',
    'monthly payment breakdown',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/amortization-calculator',
  },
  openGraph: {
    title: 'Amortization Calculator - Create Detailed Loan Amortization Schedules',
    description: 'Free amortization calculator with extra payment options. Get monthly and yearly amortization schedules, total interest, and principal breakdown.',
    url: 'https://www.thetutorbridge.com/calculators/amortization-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Amortization Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Amortization Calculator - Calculate Loan Amortization Schedules',
    description: 'Calculate loan amortization with extra payments. Get detailed schedules showing monthly principal, interest, and balance.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function AmortizationCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
