import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'College GPA Calculator - Calculate Semester & Cumulative GPA | The Tutor Bridge',
  description: 'Free college GPA calculator to calculate semester and cumulative GPA with credit hours. Track academic performance, calculate weighted GPA, and plan your grades with comprehensive examples and grading scales.',
  keywords: [
    'college gpa calculator',
    'gpa calculator',
    'calculate gpa',
    'cumulative gpa calculator',
    'semester gpa calculator',
    'how to calculate gpa',
    'gpa calculator with credits',
    'weighted gpa calculator',
    'university gpa calculator',
    'college grade calculator',
    'grade point average calculator',
    'free gpa calculator',
    'online gpa calculator',
    'gpa calculator 4.0 scale',
    'calculate my gpa',
    'college grades calculator',
    'academic gpa calculator',
    'how to calculate college gpa',
    'gpa calculation formula',
    'credit hour gpa calculator',
    'semester grade calculator',
    'cumulative grade point average',
    'calculate semester gpa',
    'calculate cumulative gpa',
    'gpa calculator by semester',
    'college transcript calculator',
    'undergraduate gpa calculator',
    'graduate gpa calculator',
    'bachelors gpa calculator',
    'masters gpa calculator',
    'gpa calculator for college students',
    'calculate gpa with letter grades',
    'a b c grade calculator',
    'gpa from letter grades',
    'credit weighted gpa',
    'how to find gpa',
    'what is my gpa',
    'gpa tracker',
    'grade calculator college',
    'academic performance calculator',
    'college gpa calculation',
    'semester credit hours calculator',
    'gpa planning calculator',
    'target gpa calculator',
    'improve gpa calculator',
    'gpa maintenance calculator',
    '4.0 gpa calculator',
    'honor roll gpa calculator',
    'deans list gpa calculator',
    'scholarship gpa calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/college-gpa-calculator',
  },
  openGraph: {
    title: 'College GPA Calculator - Calculate Semester & Cumulative GPA',
    description: 'Free college GPA calculator to calculate semester and cumulative GPA with credit hours. Track academic performance and plan your grades.',
    url: 'https://www.thetutorbridge.com/calculators/college-gpa-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'College GPA Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'College GPA Calculator - Calculate Semester & Cumulative GPA',
    description: 'Calculate semester and cumulative GPA with credit hours. Free college GPA calculator with comprehensive examples.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function CollegeGPACalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
