import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Watt Calculator - Calculate Voltage, Current, Resistance & Power | The Tutor Bridge',
  description: 'Free watt calculator with Ohm\'s Law. Calculate power (watts), voltage (volts), current (amps), and resistance (ohms) with step-by-step solutions. Supports unit conversions from mW to GW, mA to A, mV to kV, and mΩ to MΩ.',
  keywords: [
    'watt calculator',
    'watts calculator',
    'power calculator',
    'voltage calculator',
    'current calculator',
    'resistance calculator',
    'ohms law calculator',
    'electrical power calculator',
    'calculate watts',
    'calculate voltage',
    'calculate current',
    'calculate resistance',
    'P=VI calculator',
    'P=I²R calculator',
    'P=V²/R calculator',
    'V=IR calculator',
    'ohm law formula',
    'watt formula',
    'power formula',
    'electrical formula calculator',
    'volts to watts',
    'amps to watts',
    'watts to amps',
    'watts to volts',
    'kilowatt calculator',
    'milliwatt calculator',
    'megawatt calculator',
    'gigawatt calculator',
    'voltage current resistance',
    'electrical circuit calculator',
    'power equation',
    'wattage calculator',
    'electric power calculator',
    'W=VA calculator',
    'joules per second',
    'electrical calculations',
    'circuit power calculator',
    'electronics calculator',
    'physics calculator',
    'electricity calculator',
    'power consumption calculator',
    'electrical engineering calculator',
    'V=P/I calculator',
    'I=P/V calculator',
    'R=V/I calculator',
    'free watt calculator',
    'online watt calculator',
    'watt calculator with steps',
    'ohms law formula calculator',
    'electrical power formula',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/watt-calculator',
  },
  openGraph: {
    title: 'Watt Calculator - Calculate Power, Voltage, Current & Resistance',
    description: 'Calculate watts, volts, amps, and ohms using Ohm\'s Law with step-by-step solutions. Free electrical power calculator with unit conversions.',
    url: 'https://www.thetutorbridge.com/calculators/watt-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Watt Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Watt Calculator - Free Electrical Power Tool',
    description: 'Calculate power, voltage, current, and resistance with Ohm\'s Law. Step-by-step solutions included.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function WattCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
