import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Money Calculator - Count Cash, Coins & Currency with Breakdown | The Tutor Bridge',
  description: 'Free money counting calculator to count banknotes, coins, and rolled coins with detailed breakdown. Calculate total cash value, organize currency denominations, and get comprehensive money counting solutions.',
  keywords: [
    'money calculator',
    'money counter',
    'cash calculator',
    'coin counter',
    'currency calculator',
    'money counting calculator',
    'count money',
    'cash counter',
    'banknote calculator',
    'bill counter',
    'change calculator',
    'money counter online',
    'free money calculator',
    'money counting tool',
    'cash counting calculator',
    'currency counter',
    'money denomination calculator',
    'count bills and coins',
    'money organizer',
    'cash register calculator',
    'money total calculator',
    'bill and coin calculator',
    'money breakdown calculator',
    'cash drawer calculator',
    'banknote counter',
    'coin value calculator',
    'currency counting tool',
    'money adding calculator',
    'count currency',
    'money sum calculator',
    'dollar counter',
    'cent counter',
    'penny counter',
    'nickel counter',
    'dime counter',
    'quarter counter',
    'money sorting calculator',
    'cash management calculator',
    'money denomination counter',
    'retail cash calculator',
    'bank deposit calculator',
    'till calculator',
    'money counting machine',
    'digital money counter',
    'how to count money',
    'money counting methods',
    'currency denomination',
    'count rolled coins',
    'coin roll calculator',
    'money verification tool',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/money-calculator',
  },
  openGraph: {
    title: 'Money Calculator - Count Cash & Coins with Breakdown',
    description: 'Free money counting calculator with detailed breakdown. Count banknotes, coins, and rolled coins. Get instant total value with denomination-by-denomination calculation.',
    url: 'https://www.thetutorbridge.com/calculators/money-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Money Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Money Calculator - Free Cash Counter Tool',
    description: 'Count banknotes, coins, and rolled coins with detailed breakdown. Get instant money total with denomination-by-denomination calculation.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MoneyCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
