import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dice Roller - Free Online Dice Rolling Simulator for D&D, RPGs & Board Games | The Tutor Bridge',
  description: 'Free online dice roller with multiple dice types (d4, d6, d8, d10, d12, d20, d100). Roll virtual dice for D&D, tabletop RPGs, board games, and probability learning with animations.',
  keywords: [
    'dice roller',
    'online dice roller',
    'virtual dice roller',
    'free dice roller',
    'roll dice online',
    'dice simulator',
    'd20 dice roller',
    'd6 dice roller',
    'multiple dice roller',
    'dice roller d&d',
    'dnd dice roller',
    'dungeons and dragons dice',
    'rpg dice roller',
    'tabletop dice roller',
    'polyhedral dice roller',
    'd4 dice',
    'd6 dice',
    'd8 dice',
    'd10 dice',
    'd12 dice',
    'd20 dice',
    'd100 dice',
    'percentile dice',
    'dice roller with modifier',
    'custom dice roller',
    'multiple dice',
    'roll multiple dice',
    'dice probability',
    'random dice roller',
    'board game dice',
    'game dice roller',
    'dice rolling simulator',
    'digital dice',
    'virtual dice',
    'animated dice roller',
    'dice roll calculator',
    'dice roller tool',
    'dice statistics',
    'dice sum calculator',
    'fair dice roller',
    'random number dice',
    'dice generator',
    'probability dice',
    'dice roller for teachers',
    'classroom dice roller',
    'math dice roller',
    'dice probability calculator',
    'polyhedral dice',
    'dice types',
    'roll the dice',
    'online dice',
    'dice roller app',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/dice-roller',
  },
  openGraph: {
    title: 'Dice Roller - Online Virtual Dice for D&D, RPGs & Games',
    description: 'Free online dice roller with d4, d6, d8, d10, d12, d20, and d100 dice. Perfect for D&D, tabletop RPGs, board games, and learning probability.',
    url: 'https://thetutorbridge.com/calculators/dice-roller',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Dice Roller - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Dice Roller - Online Virtual Dice for D&D, RPGs & Games',
    description: 'Roll virtual dice online with our free dice roller. Supports all polyhedral dice types with animations for gaming and probability.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function DiceRollerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
