import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Calorie Calculator - Free Daily Calorie Needs Calculator for Weight Loss & Maintenance | The Tutor Bridge',
  description: 'Free calorie calculator to estimate daily calorie needs for weight loss, maintenance, and muscle gain. Uses Mifflin-St Jeor, Harris-Benedict, and Katch-McArdle formulas with BMR calculation.',
  keywords: [
    'calorie calculator',
    'daily calorie calculator',
    'calorie needs calculator',
    'calculate calories',
    'free calorie calculator',
    'online calorie calculator',
    'calorie counter',
    'how many calories',
    'calories per day',
    'daily calorie intake',
    'calorie intake calculator',
    'weight loss calorie calculator',
    'calorie calculator for weight loss',
    'calories to lose weight',
    'weight gain calorie calculator',
    'calories to gain weight',
    'maintenance calorie calculator',
    'maintenance calories',
    'bmr calculator',
    'basal metabolic rate calculator',
    'calculate bmr',
    'mifflin st jeor calculator',
    'harris benedict calculator',
    'katch mcardle calculator',
    'tdee calculator',
    'total daily energy expenditure',
    'calorie deficit calculator',
    'calorie surplus calculator',
    'calories for men',
    'calories for women',
    'calorie calculator with activity level',
    'activity level calculator',
    'sedentary calorie calculator',
    'active calorie calculator',
    'calorie needs by age',
    'calorie calculator metric',
    'calorie calculator imperial',
    'calories to maintain weight',
    'how many calories to eat',
    'calorie counting',
    'macros calculator',
    'nutrition calculator',
    'diet calculator',
    'fitness calorie calculator',
    'weight management calculator',
    'calorie requirements',
    'daily energy needs',
    'metabolism calculator',
    'resting metabolic rate',
    'calorie burn calculator',
    'exercise calorie calculator',
    'body fat calorie calculator',
    'lean mass calculator',
    'zigzag calorie cycling',
    'calorie deficit for weight loss',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/calorie-calculator',
  },
  openGraph: {
    title: 'Calorie Calculator - Calculate Daily Calorie Needs',
    description: 'Free calorie calculator for weight loss, maintenance, and muscle gain. Calculate BMR and TDEE using proven formulas with activity level adjustment.',
    url: 'https://thetutorbridge.com/calculators/calorie-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Calorie Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Calorie Calculator - Calculate Daily Calorie Needs',
    description: 'Calculate your daily calorie needs for weight loss, maintenance, or muscle gain with our free calculator using proven BMR formulas.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function CalorieCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
