import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'EZ Grader - Easy Grade Calculator & Grading Chart | The Tutor Bridge',
  description: 'Free EZ Grader calculator to quickly convert test scores to letter grades and percentages. Generate printable grading charts, calculate scores out of any total, and grade papers fast with customizable grading scales.',
  keywords: [
    'ez grader',
    'easy grader',
    'grading calculator',
    'grade calculator',
    'test grader',
    'score calculator',
    'grading chart',
    'printable grading chart',
    'teacher grading tool',
    'grading scale calculator',
    'percentage to grade',
    'score to grade converter',
    'test score calculator',
    'quiz grader',
    'assignment grader',
    'grading wheel',
    'ez grader online',
    'free grading calculator',
    'teacher calculator',
    'classroom grading tool',
    'grade percentage calculator',
    'points to grade',
    'calculate test grade',
    'grading helper',
    'teacher grading assistant',
    'score percentage calculator',
    'wrong answers to grade',
    'missed questions calculator',
    'grading scale chart',
    'custom grading scale',
    'letter grade calculator',
    'a b c grade calculator',
    'grading rubric calculator',
    'education grading tool',
    'classroom assessment tool',
    'quick grade calculator',
    'instant grading',
    'grade lookup table',
    'grading reference chart',
    'teacher time saver',
    'grading made easy',
    'simple grading calculator',
    'fast grading tool',
    'grade conversion chart',
    'percentage grade chart',
    'score grade chart',
    'grading system calculator',
    'academic grading calculator',
    'student score calculator',
    'test scoring tool',
    'quiz scoring calculator',
    'exam grader',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/ez-grader',
  },
  openGraph: {
    title: 'EZ Grader - Easy Grade Calculator & Printable Grading Chart',
    description: 'Free online EZ Grader to convert test scores to letter grades instantly. Generate grading charts, calculate percentages, and grade papers quickly.',
    url: 'https://www.thetutorbridge.com/calculators/ez-grader',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'EZ Grader Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'EZ Grader - Easy Grade Calculator & Grading Chart',
    description: 'Convert test scores to letter grades instantly with our free EZ Grader calculator. Printable grading charts included.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function EZGraderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
