import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Mean Median Mode Calculator - Free Statistics Calculator with Range & Quartiles | The Tutor Bridge',
  description: 'Free mean, median, mode calculator with complete statistical analysis. Calculate average, median, mode, range, quartiles, IQR, and outliers instantly. Perfect for students learning statistics with step-by-step explanations.',
  keywords: [
    'mean median mode calculator',
    'mean calculator',
    'median calculator',
    'mode calculator',
    'statistics calculator',
    'average calculator',
    'mean median mode range calculator',
    'how to calculate mean median mode',
    'how to find mean',
    'how to find median',
    'how to find mode',
    'average mean median mode',
    'statistical calculator',
    'measures of central tendency',
    'measures of central tendency calculator',
    'quartile calculator',
    'interquartile range calculator',
    'IQR calculator',
    'range calculator',
    'outlier calculator',
    'data set calculator',
    'descriptive statistics calculator',
    'math statistics calculator',
    'free statistics calculator',
    'online mean median mode calculator',
    'mean median mode calculator with steps',
    'calculate average',
    'find median',
    'find mode',
    'central tendency',
    'statistical analysis tool',
    'data analysis calculator',
    'variance calculator',
    'standard deviation calculator',
    'statistical measures',
    'math calculator statistics',
    'statistics homework help',
    'mean median mode range',
    'how to calculate quartiles',
    'Q1 Q2 Q3 calculator',
    'first quartile calculator',
    'third quartile calculator',
    'median quartile calculator',
    'outliers detection calculator',
    'box plot calculator',
    'five number summary calculator',
    'educational statistics tool',
    'student statistics calculator',
    'statistics for beginners',
    'learn statistics',
    'statistics explained',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/mean-mode-median-calculator',
  },
  openGraph: {
    title: 'Mean Median Mode Calculator - Complete Statistical Analysis',
    description: 'Free statistics calculator with mean, median, mode, range, quartiles, and outliers detection. Get instant results with detailed explanations.',
    url: 'https://www.thetutorbridge.com/calculators/mean-mode-median-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Mean Median Mode Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Mean Median Mode Calculator - Free Statistics Tool',
    description: 'Calculate mean, median, mode, range, quartiles, and identify outliers with step-by-step solutions. Perfect for statistics students.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MeanMedianModeCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
