import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Fraction to Decimal Calculator - Free Converter with Steps | The Tutor Bridge',
  description: 'Free fraction to decimal calculator with step-by-step solutions. Convert any fraction to decimal with GCF reduction and long division explanation. Perfect for students learning decimal conversion.',
  keywords: [
    'fraction to decimal calculator',
    'fraction to decimal',
    'convert fraction to decimal',
    'fraction decimal converter',
    'decimal conversion calculator',
    'fraction converter',
    'how to convert fraction to decimal',
    'fraction to decimal formula',
    'free fraction to decimal calculator',
    'online fraction to decimal',
    'fraction to decimal with steps',
    'fraction to decimal conversion',
    'decimal calculator',
    'fraction calculator',
    'convert fractions',
    'fraction to decimal chart',
    'fraction to percentage to decimal',
    'improper fraction to decimal',
    'proper fraction to decimal',
    'mixed number to decimal',
    'numerator denominator to decimal',
    'fraction division to decimal',
    'gcf fraction to decimal',
    'simplify fraction to decimal',
    'reduce fraction to decimal',
    'fraction to decimal solver',
    'fraction to decimal converter online',
    'how to change fraction to decimal',
    'turning fractions into decimals',
    'math fraction to decimal',
    'fraction to decimal step by step',
    'fraction to decimal calculator with work',
    'educational fraction calculator',
    'student fraction to decimal',
    'fraction decimal conversion tool',
    'fraction to decimal helper',
    'fraction to decimal for students',
    'learn fraction to decimal',
    'fraction to decimal practice',
    'fraction to decimal examples',
    'fraction to decimal math',
    'convert fraction to decimal online free',
    'fraction to decimal rounding',
    'fraction to decimal precision',
    'long division fraction to decimal',
    'fraction to decimal with rounding',
    'fraction to decimal calculator free',
    'best fraction to decimal calculator',
    'accurate fraction to decimal',
    'fraction to decimal conversion chart',
    'fraction to decimal worksheet',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/fraction-to-decimal-calculator',
  },
  openGraph: {
    title: 'Fraction to Decimal Calculator - Free Converter with Steps',
    description: 'Free fraction to decimal calculator with step-by-step solutions. Convert fractions to decimals with GCF reduction and detailed explanations.',
    url: 'https://thetutorbridge.com/calculators/fraction-to-decimal-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Fraction to Decimal Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Fraction to Decimal Calculator - Free Tool with Steps',
    description: 'Convert fractions to decimals instantly with step-by-step solutions and GCF reduction.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function FractionToDecimalCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
