import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Gratuity Calculator - Calculate Gratuity as per Act 1972 | The Tutor Bridge',
  description: 'Free gratuity calculator as per Payment of Gratuity Act 1972. Calculate retirement gratuity, tax exemption, and eligibility. Perfect for employees with 5+ years service.',
  keywords: [
    'gratuity calculator',
    'gratuity calculator india',
    'payment of gratuity calculator',
    'gratuity calculation formula',
    'how to calculate gratuity',
    'gratuity calculator online',
    'free gratuity calculator',
    'gratuity amount calculator',
    'retirement gratuity calculator',
    'gratuity eligibility calculator',
    'gratuity act 1972 calculator',
    'gratuity tax calculator',
    'gratuity exemption calculator',
    'employee gratuity calculator',
    'gratuity on resignation',
    'gratuity on retirement',
    'gratuity formula',
    'how much gratuity will i get',
    'gratuity calculation after 5 years',
    'gratuity calculation after 10 years',
    'gratuity calculation after 20 years',
    'maximum gratuity limit',
    'gratuity cap 20 lakh',
    'when is gratuity paid',
    'gratuity payment rules',
    'gratuity calculator as per law',
    'private sector gratuity',
    'government gratuity calculator',
    'gratuity partial years',
    'gratuity basic salary',
    'gratuity da calculation',
    'gratuity claim calculator',
    'gratuity forfeiture',
    'gratuity nomination',
    'form f gratuity',
    'gratuity withdrawal rules',
    'gratuity eligibility 5 years',
    'continuous service gratuity',
    'gratuity on death',
    'gratuity tax exemption section 10(10)',
    'gratuity maximum limit 2026',
    'gratuity calculation example',
    'how to claim gratuity',
    'gratuity documents required',
    'employer gratuity liability',
    'gratuity maturity calculator',
    'separation gratuity calculator',
    'voluntary retirement gratuity',
    'superannuation gratuity',
    'gratuity fund calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/gratuity-calculator',
  },
  openGraph: {
    title: 'Gratuity Calculator - Calculate as per Act 1972 | The Tutor Bridge',
    description: 'Calculate your gratuity amount based on Payment of Gratuity Act 1972. Free calculator with tax exemption details and eligibility check.',
    url: 'https://www.thetutorbridge.com/calculators/gratuity-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Gratuity Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Gratuity Calculator - As per Act 1972',
    description: 'Calculate your retirement gratuity amount with tax exemption details. Free online calculator.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function GratuityCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
