import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'LCM Calculator - Least Common Multiple Calculator with Steps | The Tutor Bridge',
  description: 'Free LCM calculator to find the Least Common Multiple of 2 or more numbers. Shows step-by-step solutions using prime factorization, listing multiples, and division methods. Perfect for students learning LCM.',
  keywords: [
    'lcm calculator',
    'least common multiple calculator',
    'lcm',
    'least common multiple',
    'lowest common multiple',
    'find lcm',
    'calculate lcm',
    'lcm of 2 numbers',
    'lcm of 3 numbers',
    'lcm of multiple numbers',
    'how to find lcm',
    'lcm formula',
    'lcm calculator with steps',
    'free lcm calculator',
    'online lcm calculator',
    'lcm solver',
    'lcm finder',
    'multiple numbers lcm',
    'lcm and gcf',
    'lcm and hcf',
    'prime factorization lcm',
    'listing multiples method',
    'division method lcm',
    'lcm calculator online',
    'lcm calculator free',
    'least common multiple finder',
    'lowest common multiple calculator',
    'lcm calculator step by step',
    'lcm calculator with work',
    'how to calculate lcm',
    'lcm calculation',
    'lcm method',
    'lcm examples',
    'lcm problems',
    'lcm for students',
    'educational lcm calculator',
    'math lcm calculator',
    'lcm help',
    'lcm practice',
    'lcm worksheet',
    'lcm and gcf calculator',
    'common multiple calculator',
    'multiples calculator',
    'lcm word problems',
    'lcm real world applications',
    'lcm explained',
    'understanding lcm',
    'lcm tricks',
    'lcm shortcuts',
    'lcm tips',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/lcm-calculator',
  },
  openGraph: {
    title: 'LCM Calculator - Least Common Multiple with Steps',
    description: 'Free LCM calculator for 2+ numbers. Find the Least Common Multiple with step-by-step solutions using multiple methods.',
    url: 'https://www.thetutorbridge.com/calculators/lcm-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'LCM Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LCM Calculator - Free Tool with Steps',
    description: 'Calculate Least Common Multiple of 2+ numbers instantly with detailed step-by-step explanations.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function LCMCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
