import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Markup Calculator - Calculate Markup Percentage, Cost & Selling Price | The Tutor Bridge',
  description: 'Free markup calculator with step-by-step solutions. Calculate markup percentage, selling price from cost, profit, and convert between markup and margin. Perfect for business pricing, retail, and wholesale calculations.',
  keywords: [
    'markup calculator',
    'markup percentage calculator',
    'calculate markup',
    'markup formula',
    'how to calculate markup',
    'markup vs margin',
    'markup percentage',
    'price markup calculator',
    'retail markup calculator',
    'wholesale markup calculator',
    'product markup calculator',
    'markup calculation',
    'markup price calculator',
    'cost to selling price calculator',
    'selling price from markup',
    'markup to margin converter',
    'margin to markup converter',
    'business markup calculator',
    'profit markup calculator',
    'markup percentage formula',
    'what is markup',
    'markup definition',
    'markup meaning',
    'markup in business',
    'gross markup calculator',
    'net markup calculator',
    'markup pricing strategy',
    'calculate selling price',
    'calculate profit from markup',
    'markup rate calculator',
    'markup multiplier calculator',
    'keystone markup',
    'standard markup',
    'cost plus markup',
    'markup based pricing',
    'free markup calculator',
    'online markup calculator',
    'markup calculator with steps',
    'retail pricing calculator',
    'wholesale pricing calculator',
    'product pricing calculator',
    'how to markup products',
    'markup for profit',
    'markup example',
    'markup problems',
    'markup math',
    'markup percentage from cost',
    'markup on cost formula',
    'markup on selling price',
    'calculate markup from margin',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/markup-calculator',
  },
  openGraph: {
    title: 'Markup Calculator - Calculate Markup Percentage & Selling Price',
    description: 'Calculate markup percentage, selling price, and profit with step-by-step solutions. Convert between markup and margin. Free tool for business pricing.',
    url: 'https://thetutorbridge.com/calculators/markup-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Markup Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Markup Calculator - Free Tool',
    description: 'Calculate markup percentage and selling price with detailed step-by-step solutions. Free business pricing calculator.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MarkupCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
