import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Percent Error Calculator - Calculate Percentage Error with Formula | The Tutor Bridge',
  description: 'Free percent error calculator. Calculate percentage error between experimental and theoretical values with step-by-step solutions. Includes absolute error and relative error calculations with proper mathematical notation.',
  keywords: [
    'percent error calculator',
    'percentage error calculator',
    'calculate percent error',
    'percent error formula',
    'how to calculate percent error',
    'free percent error calculator',
    'online percent error calculator',
    'experimental error calculator',
    'theoretical value calculator',
    'measurement error calculator',
    'scientific error calculator',
    'chemistry percent error',
    'physics percent error',
    'laboratory error calculator',
    'error analysis calculator',
    'absolute error calculator',
    'relative error calculator',
    'experimental value calculator',
    'percent difference calculator',
    'accuracy calculator',
    'precision calculator',
    'measurement uncertainty',
    'error percentage',
    'calculate measurement error',
    'science error calculator',
    'lab percent error',
    'percent error equation',
    'error formula calculator',
    'experimental vs theoretical',
    'calculate experimental error',
    'percentage deviation calculator',
    'error margin calculator',
    'accuracy percentage calculator',
    'scientific measurement error',
    'chemistry lab error',
    'physics lab error',
    'biology error calculator',
    'statistics error calculator',
    'data analysis error',
    'quantitative error',
    'measurement deviation',
    'experimental accuracy',
    'theoretical accuracy',
    'percent error solver',
    'error calculation tool',
    'scientific calculator error',
    'lab report calculator',
    'research error calculator',
    'data error calculator',
    'experimental data calculator',
    'measurement analysis',
    'error analysis tool',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/percent-error-calculator',
  },
  openGraph: {
    title: 'Percent Error Calculator - Calculate Percentage Error with Formula',
    description: 'Calculate percentage error between experimental and theoretical values with step-by-step solutions. Free tool for scientific measurements and lab reports.',
    url: 'https://www.thetutorbridge.com/calculators/percent-error-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Percent Error Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Percent Error Calculator - Free Tool',
    description: 'Calculate percentage error with step-by-step solutions. Perfect for chemistry, physics, and lab reports.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function PercentErrorCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
