import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Simplifying Fractions Calculator - Free Fraction Simplifier with Steps | The Tutor Bridge',
  description: 'Free simplifying fractions calculator with step-by-step solutions. Reduce fractions to simplest form using GCF method. Convert improper fractions to mixed numbers. Perfect for students learning fraction simplification.',
  keywords: [
    'simplifying fractions calculator',
    'simplify fractions',
    'fraction simplifier',
    'reduce fractions calculator',
    'simplify fractions calculator',
    'fraction reducer',
    'how to simplify fractions',
    'simplifying fractions',
    'reduce fractions',
    'simplest form calculator',
    'lowest terms calculator',
    'fraction simplification',
    'gcf fraction calculator',
    'greatest common factor fractions',
    'simplify fraction to lowest terms',
    'free fraction simplifier',
    'online fraction simplifier',
    'simplifying fractions with steps',
    'simplify improper fractions',
    'reduce improper fractions',
    'fraction to mixed number',
    'improper fraction to mixed number calculator',
    'simplify mixed numbers',
    'simplifying fractions examples',
    'fraction simplification calculator',
    'simplifying fractions tool',
    'reduce fraction to simplest form',
    'simplify fractions step by step',
    'fraction simplifier with work',
    'how to reduce fractions',
    'simplifying fractions for students',
    'math fraction simplifier',
    'simplifying fractions help',
    'fraction reduction calculator',
    'simplify fractions online free',
    'educational fraction calculator',
    'student fraction simplifier',
    'learn to simplify fractions',
    'simplifying fractions practice',
    'fraction simplification steps',
    'gcf method fractions',
    'prime factorization fractions',
    'common factor fractions',
    'simplifying fractions worksheet',
    'fraction simplifier calculator online',
    'best fraction simplifier',
    'accurate fraction reducer',
    'simplifying fractions made easy',
    'simplifying fractions rules',
    'simplifying fractions formulas',
    'simplifying complex fractions',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/simplifying-fractions-calculator',
  },
  openGraph: {
    title: 'Simplifying Fractions Calculator - Free Fraction Simplifier with Steps',
    description: 'Free simplifying fractions calculator with step-by-step solutions. Reduce fractions to simplest form using GCF. Convert improper fractions to mixed numbers.',
    url: 'https://www.thetutorbridge.com/calculators/simplifying-fractions-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Simplifying Fractions Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Simplifying Fractions Calculator - Free Tool with Steps',
    description: 'Simplify fractions instantly with step-by-step solutions using GCF method. Convert improper fractions to mixed numbers.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function SimplifyingFractionsCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
