import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Percentage to CGPA Calculator - Convert % to CGPA with Formula & Examples | The Tutor Bridge',
  description: 'Free Percentage to CGPA calculator with comprehensive conversion formulas, step-by-step examples, and grading systems. Convert your percentage to CGPA (4.0, 10.0 scale) instantly with detailed explanations.',
  keywords: [
    'percentage to cgpa calculator',
    'convert percentage to cgpa',
    'percentage to cgpa',
    'cgpa calculator',
    'percentage to cgpa conversion',
    'marks to cgpa calculator',
    'percentage to cgpa formula',
    'how to convert percentage to cgpa',
    'percentage cgpa converter',
    'cgpa conversion calculator',
    'percentage to 10 point cgpa',
    'percentage to 4 point cgpa',
    'percentage to cgpa conversion formula',
    'percentage to cgpa calculation',
    'calculate cgpa from percentage',
    'cgpa converter',
    'free cgpa calculator',
    'online percentage to cgpa',
    'percentage to cgpa online calculator',
    'university percentage to cgpa',
    'college percentage to cgpa',
    'engineering percentage to cgpa',
    'cbse percentage to cgpa',
    'ignou percentage to cgpa',
    'cgpa grading system',
    'cumulative grade point average',
    'percentage to gpa',
    'grade point average calculator',
    'cgpa calculation method',
    'cgpa scoring system',
    'percentage cgpa table',
    'percentage to cgpa chart',
    'percentage marks conversion',
    'academic cgpa calculator',
    'semester percentage to cgpa',
    'overall percentage to cgpa',
    'percentage cgpa equivalence',
    'percentage to cgpa examples',
    'percentage conversion examples',
    'how percentage converts to cgpa',
    'cgpa formula',
    'cgpa meaning',
    'difference between percentage and cgpa',
    'percentage vs cgpa',
    'percentage to cgpa india',
    'percentage to cgpa scale',
    'percentage grade conversion',
    'percentage point system',
    'learn cgpa conversion',
    'understand cgpa',
    'cgpa help',
    'cgpa interpretation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/percentage-to-cgpa-calculator',
  },
  openGraph: {
    title: 'Percentage to CGPA Calculator - Convert % to CGPA with Formula',
    description: 'Convert percentage to CGPA instantly with comprehensive formulas and examples. Supports 4.0, 10.0 grading scales with step-by-step conversion.',
    url: 'https://thetutorbridge.com/calculators/percentage-to-cgpa-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Percentage to CGPA Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Percentage to CGPA Calculator - Free Tool',
    description: 'Convert percentage to CGPA with formulas and examples. Supports multiple grading scales.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function PercentageToCGPACalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
