import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'BMR Calculator - Free Basal Metabolic Rate & TDEE Calculator | The Tutor Bridge',
  description: 'Free BMR calculator to calculate your Basal Metabolic Rate and daily calorie needs. Uses Mifflin-St Jeor, Harris-Benedict, and Katch-McArdle formulas. Get TDEE for all activity levels.',
  keywords: [
    'bmr calculator',
    'basal metabolic rate calculator',
    'bmr calc',
    'calculate bmr',
    'bmr formula calculator',
    'metabolic rate calculator',
    'resting metabolic rate calculator',
    'rmr calculator',
    'bmr and tdee calculator',
    'tdee calculator',
    'total daily energy expenditure',
    'daily calorie calculator',
    'calories burned at rest',
    'metabolism calculator',
    'calorie needs calculator',
    'how many calories do i burn',
    'mifflin st jeor calculator',
    'harris benedict calculator',
    'katch mcardle calculator',
    'bmr calculator online',
    'free bmr calculator',
    'accurate bmr calculator',
    'bmr calculator with activity level',
    'bmr calculator metric',
    'bmr calculator imperial',
    'bmr calculator for weight loss',
    'bmr calculator for muscle gain',
    'bmr calculator men',
    'bmr calculator women',
    'bmr calculator age',
    'bmr calculator body fat',
    'lean body mass calculator',
    'resting energy expenditure',
    'ree calculator',
    'maintenance calories calculator',
    'calorie deficit calculator',
    'calorie surplus calculator',
    'weight loss calorie calculator',
    'weight gain calorie calculator',
    'fitness calculator',
    'nutrition calculator',
    'diet calculator',
    'energy expenditure calculator',
    'daily energy needs',
    'caloric needs calculator',
    'how to calculate bmr',
    'what is bmr',
    'bmr meaning',
    'bmr vs rmr',
    'bmr vs tdee',
    'factors affecting bmr',
    'how to increase bmr',
    'bmr for weight management',
    'scientific bmr calculator',
    'precise bmr calculation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/bmr-calculator',
  },
  openGraph: {
    title: 'BMR Calculator - Calculate Basal Metabolic Rate & Daily Calorie Needs',
    description: 'Free BMR and TDEE calculator using 3 scientific formulas. Calculate your basal metabolic rate and daily calorie needs for all activity levels.',
    url: 'https://www.thetutorbridge.com/calculators/bmr-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'BMR Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BMR Calculator - Calculate Your Basal Metabolic Rate',
    description: 'Calculate BMR and TDEE with 3 scientific formulas. Get daily calorie needs for weight loss, maintenance, or muscle gain.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function BMRCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
