import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Simple Interest Calculator - Calculate SI, Principal, Rate & Time with Formula | The Tutor Bridge',
  description: 'Free simple interest calculator to compute interest, principal, rate, time, or total amount using the formula A = P(1 + rt). Get step-by-step solutions for loans, deposits, and investments with comprehensive explanations.',
  keywords: [
    'simple interest calculator',
    'SI calculator',
    'simple interest formula',
    'A = P(1 + rt)',
    'interest calculator',
    'principal calculator',
    'rate calculator',
    'time calculator',
    'loan interest calculator',
    'deposit interest calculator',
    'investment interest calculator',
    'simple interest vs compound interest',
    'calculate simple interest',
    'calculate principal',
    'calculate interest rate',
    'calculate time period',
    'simple interest problems',
    'simple interest solver',
    'interest rate formula',
    'principal amount formula',
    'time period formula',
    'I = Prt',
    'financial calculator',
    'banking calculator',
    'savings calculator',
    'simple interest online',
    'free interest calculator',
    'simple interest examples',
    'simple interest step by step',
    'loan calculator simple interest',
    'deposit calculator',
    'investment calculator',
    'interest calculation',
    'financial mathematics',
    'basic interest calculator',
    'simple interest computation',
    'interest earned calculator',
    'total amount calculator',
    'simple interest explanation',
    'simple interest applications',
    'short-term loan calculator',
    'treasury bill calculator',
    'promissory note calculator',
    'annual interest calculator',
    'monthly interest calculator',
    'daily interest calculator',
    'interest conversion',
    'principal calculation',
    'rate calculation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/simple-interest-calculator',
  },
  openGraph: {
    title: 'Simple Interest Calculator - Calculate SI, Principal, Rate & Time',
    description: 'Free calculator to compute simple interest, principal, rate, time, or total amount using A = P(1 + rt). Get detailed step-by-step solutions for all calculations.',
    url: 'https://thetutorbridge.com/calculators/simple-interest-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Simple Interest Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Simple Interest Calculator - Free Tool',
    description: 'Calculate simple interest, principal, rate, time, or total amount with step-by-step solutions using the formula A = P(1 + rt).',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function SimpleInterestCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
