import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cubic Yards Calculator - Calculate Cubic Yards for All Shapes | The Tutor Bridge',
  description: 'Free cubic yards calculator. Calculate cubic yards, cubic feet, and cubic meters for rectangle, square, circle, triangle, and custom shapes. Includes cost calculator for concrete, mulch, gravel, and soil with step-by-step solutions.',
  keywords: [
    'cubic yards calculator',
    'cubic yard calculator',
    'calculate cubic yards',
    'how to calculate cubic yards',
    'cubic yards formula',
    'free cubic yards calculator',
    'online cubic yards calculator',
    'concrete calculator cubic yards',
    'mulch calculator cubic yards',
    'gravel calculator cubic yards',
    'soil calculator cubic yards',
    'dirt calculator cubic yards',
    'sand calculator cubic yards',
    'cubic yards to cubic feet',
    'cubic feet to cubic yards',
    'cubic meters to cubic yards',
    'volume calculator cubic yards',
    'area to cubic yards',
    'cubic yards cost calculator',
    'material calculator cubic yards',
    'landscaping calculator',
    'construction calculator cubic yards',
    'excavation calculator',
    'fill calculator cubic yards',
    'topsoil calculator',
    'stone calculator cubic yards',
    'rock calculator cubic yards',
    'aggregate calculator',
    'yard calculator concrete',
    'how many cubic yards',
    'cubic yardage calculator',
    'rectangle cubic yards',
    'circle cubic yards',
    'triangle cubic yards',
    'square cubic yards',
    'annulus cubic yards',
    'trapezoid cubic yards',
    'border cubic yards',
    'cubic yards per ton',
    'cubic yards conversion',
    'yd³ calculator',
    'cubic yard estimator',
    'volume in cubic yards',
    'calculate yards of concrete',
    'calculate yards of mulch',
    'building materials calculator',
    'construction materials calculator',
    'landscaping materials calculator',
    'driveway calculator cubic yards',
    'patio calculator cubic yards',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/cubic-yards-calculator',
  },
  openGraph: {
    title: 'Cubic Yards Calculator - Calculate Volume for All Shapes',
    description: 'Calculate cubic yards for concrete, mulch, gravel, and soil. Supports all shapes with cost calculator and multiple unit conversions.',
    url: 'https://www.thetutorbridge.com/calculators/cubic-yards-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Cubic Yards Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Cubic Yards Calculator - Free Tool',
    description: 'Calculate cubic yards for any shape. Perfect for concrete, mulch, gravel, and landscaping projects.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function CubicYardsCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
