import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Car Payment Calculator - Free Auto Loan & Monthly Payment Calculator with Amortization | The Tutor Bridge',
  description: 'Free car payment calculator to estimate monthly auto loan payments. Calculate total cost, interest, and amortization schedule with down payment, trade-in, sales tax, and loan terms.',
  keywords: [
    'car payment calculator',
    'auto loan calculator',
    'car loan calculator',
    'vehicle payment calculator',
    'monthly car payment',
    'calculate car payment',
    'auto payment calculator',
    'car finance calculator',
    'automobile loan calculator',
    'new car payment calculator',
    'used car payment calculator',
    'car loan payment calculator',
    'auto finance calculator',
    'vehicle loan calculator',
    'car payment estimator',
    'auto loan payment',
    'calculate monthly car payment',
    'car payment with trade in',
    'car payment with down payment',
    'car loan interest calculator',
    'total car cost calculator',
    'car amortization calculator',
    'car loan amortization schedule',
    'auto loan amortization',
    'car financing calculator',
    'car payment with sales tax',
    'auto loan interest rate',
    'car loan term calculator',
    'calculate auto loan',
    'car affordability calculator',
    'how much car can i afford',
    'car payment with interest',
    'vehicle financing calculator',
    'car down payment calculator',
    'trade in value calculator',
    'car sales tax calculator',
    'auto loan rate calculator',
    'car monthly payment',
    'auto payment estimator',
    'car loan cost calculator',
    'total interest on car loan',
    'car payment breakdown',
    'new car financing',
    'used car financing',
    'car lease vs buy',
    'auto loan comparison',
    'best car loan rates',
    'car payment options',
    'refinance car loan',
    'car loan refinance calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/car-payment-calculator',
  },
  openGraph: {
    title: 'Car Payment Calculator - Calculate Auto Loan & Monthly Payments',
    description: 'Free car payment calculator with amortization schedule. Calculate monthly payments, total interest, and total cost with trade-in, down payment, and sales tax.',
    url: 'https://thetutorbridge.com/calculators/car-payment-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Car Payment Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Car Payment Calculator - Calculate Auto Loan & Monthly Payments',
    description: 'Calculate your monthly car payment with our free calculator. Includes amortization schedule, trade-in value, down payment, and sales tax.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function CarPaymentCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
