import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CGPA to Percentage Calculator - Convert CGPA to % with Formula & Examples | The Tutor Bridge',
  description: 'Free CGPA to Percentage calculator with comprehensive conversion formulas, step-by-step examples, and grading systems. Convert your CGPA (4.0, 10.0 scale) to percentage instantly with detailed explanations.',
  keywords: [
    'cgpa to percentage calculator',
    'convert cgpa to percentage',
    'cgpa to percentage',
    'cgpa calculator',
    'cgpa to percentage conversion',
    'cgpa to marks calculator',
    'cgpa to percentage formula',
    'how to convert cgpa to percentage',
    'cgpa percentage converter',
    'cgpa conversion calculator',
    '10 point cgpa to percentage',
    '4 point cgpa to percentage',
    'cgpa to percentage conversion formula',
    'cgpa to percentage calculation',
    'calculate percentage from cgpa',
    'cgpa converter',
    'free cgpa calculator',
    'online cgpa to percentage',
    'cgpa to percentage online calculator',
    'university cgpa to percentage',
    'college cgpa to percentage',
    'engineering cgpa to percentage',
    'cbse cgpa to percentage',
    'ignou cgpa to percentage',
    'cgpa grading system',
    'cumulative grade point average',
    'gpa to percentage',
    'grade point average calculator',
    'cgpa calculation method',
    'cgpa scoring system',
    'cgpa percentage table',
    'cgpa to percentage chart',
    'cgpa marks conversion',
    'academic cgpa calculator',
    'semester cgpa to percentage',
    'overall cgpa to percentage',
    'cgpa percentage equivalence',
    'cgpa to percentage examples',
    'cgpa conversion examples',
    'how cgpa is calculated',
    'cgpa formula',
    'cgpa meaning',
    'difference between cgpa and percentage',
    'cgpa vs percentage',
    'cgpa to percentage india',
    'cgpa to percentage scale',
    'cgpa grade conversion',
    'cgpa point system',
    'learn cgpa conversion',
    'understand cgpa',
    'cgpa help',
    'cgpa interpretation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/cgpa-to-percentage-calculator',
  },
  openGraph: {
    title: 'CGPA to Percentage Calculator - Convert CGPA to % with Formula',
    description: 'Convert CGPA to percentage instantly with comprehensive formulas and examples. Supports 4.0, 10.0 grading scales with step-by-step conversion.',
    url: 'https://thetutorbridge.com/calculators/cgpa-to-percentage-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'CGPA to Percentage Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CGPA to Percentage Calculator - Free Tool',
    description: 'Convert CGPA to percentage with formulas and examples. Supports multiple grading scales.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function CGPAToPercentageCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
