import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Percentile Calculator - Calculate Any Percentile with Step-by-Step Solutions | The Tutor Bridge',
  description: 'Free percentile calculator. Calculate any percentile (1st-99th) from datasets with step-by-step solutions. Display every nth percentile option. Perfect for statistics and data analysis.',
  keywords: [
    'percentile calculator',
    'calculate percentile',
    'percentile',
    'find percentile',
    'percentile formula',
    'how to find percentile',
    'free percentile calculator',
    'online percentile calculator',
    'percentile solver',
    'percentile rank calculator',
    'percentile calculation',
    'percentile statistics',
    'nth percentile',
    'percentile position',
    'percentile method',
    'percentile value',
    '25th percentile',
    '50th percentile',
    '75th percentile',
    '90th percentile',
    '95th percentile',
    '99th percentile',
    'percentile data set',
    'percentile analysis',
    'percentile computation',
    'percentile distribution',
    'statistical percentile',
    'percentile notation',
    'percentile symbols',
    'percentile rank',
    'percentile score',
    'data percentile',
    'percentile calculation method',
    'percentile step by step',
    'every 5th percentile',
    'every 10th percentile',
    'all percentiles',
    'multiple percentiles',
    'percentile table',
    'percentile chart',
    'percentile examples',
    'learn percentile',
    'understand percentile',
    'percentile help',
    'percentile vs quartile',
    'percentile meaning',
    'percentile interpretation',
    'percentile function',
    'percentile math',
    'percentile problems',
    'percentile solutions',
    'percentile practice',
    'descriptive statistics percentile',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/percentile-calculator',
  },
  openGraph: {
    title: 'Percentile Calculator - Calculate Any Percentile with Solutions',
    description: 'Calculate any percentile (1st-99th) from datasets with step-by-step solutions. Display every nth percentile option for comprehensive analysis.',
    url: 'https://www.thetutorbridge.com/calculators/percentile-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Percentile Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Percentile Calculator - Free Tool',
    description: 'Calculate any percentile with step-by-step solutions. Display every nth percentile.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function PercentileCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
