import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Standard Deviation Calculator - Sample & Population SD Calculator | The Tutor Bridge',
  description: 'Free standard deviation calculator with step-by-step solutions. Calculate sample and population standard deviation, variance, mean, and sum of squares with detailed mathematical notation and formulas.',
  keywords: [
    'standard deviation calculator',
    'standard deviation',
    'calculate standard deviation',
    'std dev calculator',
    'sample standard deviation calculator',
    'population standard deviation calculator',
    'standard deviation formula',
    'variance calculator',
    'how to calculate standard deviation',
    'standard deviation calculator with steps',
    'free standard deviation calculator',
    'online standard deviation calculator',
    'statistics calculator',
    'sd calculator',
    's calculator',
    'sigma calculator',
    'standard deviation solver',
    'mean and standard deviation calculator',
    'sum of squares calculator',
    'variance and standard deviation',
    'calculate variance',
    'sample vs population standard deviation',
    'standard deviation of data set',
    'standard deviation step by step',
    'standard deviation math',
    'standard deviation statistics',
    'standard deviation formula calculator',
    'how to find standard deviation',
    'standard deviation example',
    'standard deviation practice',
    'standard deviation problems',
    'standard deviation help',
    'standard deviation tutoring',
    'data set standard deviation',
    'mean variance standard deviation',
    'standard deviation for students',
    'learn standard deviation',
    'understand standard deviation',
    'standard deviation explained',
    'standard deviation tool',
    'standard deviation analysis',
    'descriptive statistics calculator',
    'statistical variance calculator',
    'measure of spread calculator',
    'data dispersion calculator',
    'standard deviation n-1',
    'degrees of freedom standard deviation',
    'unbiased standard deviation',
    'standard deviation spreadsheet',
    'standard deviation dataset',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/standard-deviation-calculator',
  },
  openGraph: {
    title: 'Standard Deviation Calculator - Free Sample & Population SD Calculator',
    description: 'Calculate standard deviation, variance, mean, and sum of squares with step-by-step solutions and proper mathematical notation.',
    url: 'https://www.thetutorbridge.com/calculators/standard-deviation-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Standard Deviation Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Standard Deviation Calculator - Free Tool',
    description: 'Calculate sample and population standard deviation with detailed step-by-step solutions.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function StandardDeviationCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
