import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Quartile Calculator - Calculate Q1, Q2, Q3, IQR with Statistical Analysis | The Tutor Bridge',
  description: 'Free quartile calculator. Calculate first quartile (Q₁), second quartile (Q₂), third quartile (Q₃), interquartile range (IQR), median, min, max, and range with step-by-step solutions. Perfect for statistics students.',
  keywords: [
    'quartile calculator',
    'calculate quartiles',
    'quartile',
    'first quartile',
    'second quartile',
    'third quartile',
    'Q1 calculator',
    'Q2 calculator',
    'Q3 calculator',
    'Q1 Q2 Q3 calculator',
    'interquartile range calculator',
    'IQR calculator',
    'calculate IQR',
    'quartile statistics',
    'quartile formula',
    'how to find quartiles',
    'free quartile calculator',
    'online quartile calculator',
    'quartile solver',
    'quartile analysis',
    'quartile data set',
    'quartile median',
    'lower quartile',
    'upper quartile',
    'middle quartile',
    'quartile range',
    'quartile deviation',
    'quartile method',
    'quartile statistics calculator',
    'find quartiles',
    'quartile computation',
    'quartile distribution',
    'quartile values',
    'quartile position',
    'box plot quartiles',
    'five number summary',
    'descriptive statistics quartiles',
    'data analysis quartiles',
    'percentile quartile',
    '25th percentile',
    '50th percentile',
    '75th percentile',
    'quartile notation',
    'quartile symbols',
    'statistical quartiles',
    'quartile calculation method',
    'quartile step by step',
    'learn quartiles',
    'understand quartiles',
    'quartile help',
    'quartile examples',
    'quartile practice',
    'quartile problems',
    'quartile solutions',
    'quartile interpretation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/quartile-calculator',
  },
  openGraph: {
    title: 'Quartile Calculator - Calculate Q₁, Q₂, Q₃, and IQR',
    description: 'Calculate first, second, and third quartiles with interquartile range (IQR) and complete statistical analysis. Free tool for statistics students.',
    url: 'https://www.thetutorbridge.com/calculators/quartile-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Quartile Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Quartile Calculator - Free Tool',
    description: 'Calculate quartiles (Q₁, Q₂, Q₃) and IQR with step-by-step solutions.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function QuartileCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
