import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Height Calculator - Predict Child Adult Height | The Tutor Bridge',
  description: 'Free height calculator using Khamis-Roche and Mid-Parental methods. Predict your child\'s future adult height based on parents\' height, current height, weight, and age. Accurate height predictor for boys and girls ages 4-17.',
  keywords: [
    'height calculator',
    'child height predictor',
    'how tall will my child be',
    'future height calculator',
    'adult height predictor',
    'khamis-roche calculator',
    'khamis roche method',
    'mid-parental height calculator',
    'mid parental height',
    'child growth calculator',
    'height prediction',
    'predict adult height',
    'child height calculator',
    'baby height predictor',
    'toddler height calculator',
    'teen height predictor',
    'growth calculator',
    'height estimator',
    'future height predictor',
    'genetic height calculator',
    'parental height calculator',
    'height forecast',
    'child adult height',
    'boy height calculator',
    'girl height calculator',
    'height calculator for kids',
    'how tall will I be',
    'height prediction calculator',
    'child growth predictor',
    'pediatric height calculator',
    'height percentile calculator',
    'target height calculator',
    'expected height calculator',
    'final height predictor',
    'mature height calculator',
    'height projection',
    'height estimate calculator',
    'parents height calculator',
    'mother father height calculator',
    'hereditary height',
    'genetic height prediction',
    'child stature predictor',
    'adult stature calculator',
    'height calculator cm',
    'height calculator inches',
    'height calculator feet',
    'metric height calculator',
    'imperial height calculator',
    'free height calculator',
    'online height calculator',
    'accurate height predictor',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/height-calculator',
  },
  openGraph: {
    title: 'Height Calculator - Predict Your Child\'s Adult Height',
    description: 'Predict your child\'s future adult height using Khamis-Roche and Mid-Parental methods. Free calculator for boys and girls.',
    url: 'https://www.thetutorbridge.com/calculators/height-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Height Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Height Calculator - Child Height Predictor',
    description: 'Predict your child\'s future adult height using scientific methods. Free online calculator.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function HeightCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
