// Fraction to decimal data - 100 most popular fraction conversions
// Each fraction includes the slug, display text, decimal result, and detailed explanation

export interface FractionStep {
  description: string;
  calculation?: string;
  result?: string;
}

export interface FractionData {
  slug: string;
  numerator: number;
  denominator: number;
  fraction: string; // Display format like "1/2"
  decimal: string; // Decimal result
  decimalType: 'terminating' | 'repeating';
  repeatEnd?: string; // For repeating decimals, e.g., "0.333..."
  percentage: string;
  steps: FractionStep[];
  equivalentFractions: string[];
  simplifiedForm?: string; // If fraction can be simplified
  asPercentage: string;
  commonUses: string[];
  similarFractions: string[];
}

export const fractionsData: FractionData[] = [
  // Halves
  {
    slug: '1-2',
    numerator: 1,
    denominator: 2,
    fraction: '1/2',
    decimal: '0.5',
    decimalType: 'terminating',
    percentage: '50%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 2' },
      { description: 'Perform the division', result: '0.5' },
    ],
    equivalentFractions: ['2/4', '3/6', '4/8', '5/10', '50/100'],
    asPercentage: '50%',
    commonUses: ['Half of something', 'One part out of two equal parts', '50% in statistics'],
    similarFractions: ['1-3', '1-4', '1-5'],
  },
  // Thirds
  {
    slug: '1-3',
    numerator: 1,
    denominator: 3,
    fraction: '1/3',
    decimal: '0.333...',
    decimalType: 'repeating',
    repeatEnd: '0.333...',
    percentage: '33.33%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 3' },
      { description: 'Perform the division', result: '0.333... (repeating)' },
      { description: 'The digit 3 repeats infinitely' },
    ],
    equivalentFractions: ['2/6', '3/9', '4/12', '5/15', '10/30'],
    asPercentage: '33.33%',
    commonUses: ['One third of a whole', 'Dividing something into three equal parts', 'Probability calculations'],
    similarFractions: ['2-3', '1-2', '1-4'],
  },
  {
    slug: '2-3',
    numerator: 2,
    denominator: 3,
    fraction: '2/3',
    decimal: '0.666...',
    decimalType: 'repeating',
    repeatEnd: '0.666...',
    percentage: '66.67%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 3' },
      { description: 'Perform the division', result: '0.666... (repeating)' },
      { description: 'The digit 6 repeats infinitely' },
    ],
    equivalentFractions: ['4/6', '6/9', '8/12', '10/15', '20/30'],
    asPercentage: '66.67%',
    commonUses: ['Two thirds of a whole', 'Majority in three-part division', 'Recipe measurements'],
    similarFractions: ['1-3', '3-4', '5-6'],
  },
  // Quarters
  {
    slug: '1-4',
    numerator: 1,
    denominator: 4,
    fraction: '1/4',
    decimal: '0.25',
    decimalType: 'terminating',
    percentage: '25%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 4' },
      { description: 'Perform the division', result: '0.25' },
    ],
    equivalentFractions: ['2/8', '3/12', '4/16', '5/20', '25/100'],
    asPercentage: '25%',
    commonUses: ['Quarter of something', 'US currency (quarter = $0.25)', 'Time (quarter hour = 15 minutes)'],
    similarFractions: ['1-2', '1-3', '3-4'],
  },
  {
    slug: '3-4',
    numerator: 3,
    denominator: 4,
    fraction: '3/4',
    decimal: '0.75',
    decimalType: 'terminating',
    percentage: '75%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 4' },
      { description: 'Perform the division', result: '0.75' },
    ],
    equivalentFractions: ['6/8', '9/12', '12/16', '15/20', '75/100'],
    asPercentage: '75%',
    commonUses: ['Three quarters of something', 'Three parts out of four', 'Common measurement in cooking'],
    similarFractions: ['1-4', '2-3', '5-6'],
  },
  // Fifths
  {
    slug: '1-5',
    numerator: 1,
    denominator: 5,
    fraction: '1/5',
    decimal: '0.2',
    decimalType: 'terminating',
    percentage: '20%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 5' },
      { description: 'Perform the division', result: '0.2' },
    ],
    equivalentFractions: ['2/10', '3/15', '4/20', '5/25', '20/100'],
    asPercentage: '20%',
    commonUses: ['One fifth of something', '20% in statistics', 'Star ratings (1 out of 5 stars)'],
    similarFractions: ['1-4', '1-6', '2-5'],
  },
  {
    slug: '2-5',
    numerator: 2,
    denominator: 5,
    fraction: '2/5',
    decimal: '0.4',
    decimalType: 'terminating',
    percentage: '40%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 5' },
      { description: 'Perform the division', result: '0.4' },
    ],
    equivalentFractions: ['4/10', '6/15', '8/20', '10/25', '40/100'],
    asPercentage: '40%',
    commonUses: ['Two fifths of something', '40% in statistics', 'Portion calculations'],
    similarFractions: ['1-5', '3-5', '1-2'],
  },
  {
    slug: '3-5',
    numerator: 3,
    denominator: 5,
    fraction: '3/5',
    decimal: '0.6',
    decimalType: 'terminating',
    percentage: '60%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 5' },
      { description: 'Perform the division', result: '0.6' },
    ],
    equivalentFractions: ['6/10', '9/15', '12/20', '15/25', '60/100'],
    asPercentage: '60%',
    commonUses: ['Three fifths of something', '60% majority', 'Grading scales'],
    similarFractions: ['2-5', '4-5', '2-3'],
  },
  {
    slug: '4-5',
    numerator: 4,
    denominator: 5,
    fraction: '4/5',
    decimal: '0.8',
    decimalType: 'terminating',
    percentage: '80%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '4 ÷ 5' },
      { description: 'Perform the division', result: '0.8' },
    ],
    equivalentFractions: ['8/10', '12/15', '16/20', '20/25', '80/100'],
    asPercentage: '80%',
    commonUses: ['Four fifths of something', '80% in grading', 'High proportion measurements'],
    similarFractions: ['3-5', '3-4', '5-6'],
  },
  // Sixths
  {
    slug: '1-6',
    numerator: 1,
    denominator: 6,
    fraction: '1/6',
    decimal: '0.1666...',
    decimalType: 'repeating',
    repeatEnd: '0.1666...',
    percentage: '16.67%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 6' },
      { description: 'Perform the division', result: '0.1666... (repeating)' },
      { description: 'The digits 66 repeat infinitely after 0.1' },
    ],
    equivalentFractions: ['2/12', '3/18', '4/24', '5/30'],
    asPercentage: '16.67%',
    commonUses: ['One sixth of something', 'Dice probability (1 out of 6)', 'Dividing into six parts'],
    similarFractions: ['1-5', '1-7', '1-8'],
  },
  {
    slug: '5-6',
    numerator: 5,
    denominator: 6,
    fraction: '5/6',
    decimal: '0.8333...',
    decimalType: 'repeating',
    repeatEnd: '0.8333...',
    percentage: '83.33%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 6' },
      { description: 'Perform the division', result: '0.8333... (repeating)' },
      { description: 'The digit 3 repeats infinitely after 0.8' },
    ],
    equivalentFractions: ['10/12', '15/18', '20/24', '25/30'],
    asPercentage: '83.33%',
    commonUses: ['Five sixths of something', 'High proportion', 'Almost complete (5 out of 6)'],
    similarFractions: ['4-5', '7-8', '2-3'],
  },
  // Sevenths
  {
    slug: '1-7',
    numerator: 1,
    denominator: 7,
    fraction: '1/7',
    decimal: '0.142857...',
    decimalType: 'repeating',
    repeatEnd: '0.142857...',
    percentage: '14.29%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 7' },
      { description: 'Perform the division', result: '0.142857... (repeating)' },
      { description: 'The sequence 142857 repeats infinitely' },
    ],
    equivalentFractions: ['2/14', '3/21', '4/28', '5/35'],
    asPercentage: '14.29%',
    commonUses: ['One seventh of something', 'Weekly divisions (1 day out of 7)', 'Calendar calculations'],
    similarFractions: ['1-6', '1-8', '1-9'],
  },
  // Eighths
  {
    slug: '1-8',
    numerator: 1,
    denominator: 8,
    fraction: '1/8',
    decimal: '0.125',
    decimalType: 'terminating',
    percentage: '12.5%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 8' },
      { description: 'Perform the division', result: '0.125' },
    ],
    equivalentFractions: ['2/16', '3/24', '4/32', '5/40'],
    asPercentage: '12.5%',
    commonUses: ['One eighth of something', 'US measurements (cup = 8 fl oz)', 'Musical notes (eighth note)'],
    similarFractions: ['1-4', '1-16', '3-8'],
  },
  {
    slug: '3-8',
    numerator: 3,
    denominator: 8,
    fraction: '3/8',
    decimal: '0.375',
    decimalType: 'terminating',
    percentage: '37.5%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 8' },
      { description: 'Perform the division', result: '0.375' },
    ],
    equivalentFractions: ['6/16', '9/24', '12/32', '15/40'],
    asPercentage: '37.5%',
    commonUses: ['Three eighths of something', 'Measurements in inches', 'Carpentry and construction'],
    similarFractions: ['1-4', '1-2', '5-8'],
  },
  {
    slug: '5-8',
    numerator: 5,
    denominator: 8,
    fraction: '5/8',
    decimal: '0.625',
    decimalType: 'terminating',
    percentage: '62.5%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 8' },
      { description: 'Perform the division', result: '0.625' },
    ],
    equivalentFractions: ['10/16', '15/24', '20/32', '25/40'],
    asPercentage: '62.5%',
    commonUses: ['Five eighths of something', 'Measurements in inches', 'Carpentry measurements'],
    similarFractions: ['3-8', '7-8', '3-5'],
  },
  {
    slug: '7-8',
    numerator: 7,
    denominator: 8,
    fraction: '7/8',
    decimal: '0.875',
    decimalType: 'terminating',
    percentage: '87.5%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 8' },
      { description: 'Perform the division', result: '0.875' },
    ],
    equivalentFractions: ['14/16', '21/24', '28/32', '35/40'],
    asPercentage: '87.5%',
    commonUses: ['Seven eighths of something', 'Nearly complete portion', 'Precision measurements'],
    similarFractions: ['5-8', '3-4', '15-16'],
  },
  // Ninths
  {
    slug: '1-9',
    numerator: 1,
    denominator: 9,
    fraction: '1/9',
    decimal: '0.111...',
    decimalType: 'repeating',
    repeatEnd: '0.111...',
    percentage: '11.11%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 9' },
      { description: 'Perform the division', result: '0.111... (repeating)' },
      { description: 'The digit 1 repeats infinitely' },
    ],
    equivalentFractions: ['2/18', '3/27', '4/36', '5/45'],
    asPercentage: '11.11%',
    commonUses: ['One ninth of something', 'Dividing into nine equal parts', 'Percentage calculations'],
    similarFractions: ['1-8', '1-10', '2-9'],
  },
  {
    slug: '2-9',
    numerator: 2,
    denominator: 9,
    fraction: '2/9',
    decimal: '0.222...',
    decimalType: 'repeating',
    repeatEnd: '0.222...',
    percentage: '22.22%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 9' },
      { description: 'Perform the division', result: '0.222... (repeating)' },
      { description: 'The digit 2 repeats infinitely' },
    ],
    equivalentFractions: ['4/18', '6/27', '8/36', '10/45'],
    asPercentage: '22.22%',
    commonUses: ['Two ninths of something', 'Division problems', 'Fraction arithmetic'],
    similarFractions: ['1-9', '1-4', '4-9'],
  },
  {
    slug: '4-9',
    numerator: 4,
    denominator: 9,
    fraction: '4/9',
    decimal: '0.444...',
    decimalType: 'repeating',
    repeatEnd: '0.444...',
    percentage: '44.44%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '4 ÷ 9' },
      { description: 'Perform the division', result: '0.444... (repeating)' },
      { description: 'The digit 4 repeats infinitely' },
    ],
    equivalentFractions: ['8/18', '12/27', '16/36', '20/45'],
    asPercentage: '44.44%',
    commonUses: ['Four ninths of something', 'Fraction operations', 'Mathematical problems'],
    similarFractions: ['2-9', '5-9', '1-2'],
  },
  {
    slug: '5-9',
    numerator: 5,
    denominator: 9,
    fraction: '5/9',
    decimal: '0.555...',
    decimalType: 'repeating',
    repeatEnd: '0.555...',
    percentage: '55.56%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 9' },
      { description: 'Perform the division', result: '0.555... (repeating)' },
      { description: 'The digit 5 repeats infinitely' },
    ],
    equivalentFractions: ['10/18', '15/27', '20/36', '25/45'],
    asPercentage: '55.56%',
    commonUses: ['Five ninths of something', 'Majority in ninths', 'Mathematical calculations'],
    similarFractions: ['4-9', '7-9', '3-5'],
  },
  {
    slug: '7-9',
    numerator: 7,
    denominator: 9,
    fraction: '7/9',
    decimal: '0.777...',
    decimalType: 'repeating',
    repeatEnd: '0.777...',
    percentage: '77.78%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 9' },
      { description: 'Perform the division', result: '0.777... (repeating)' },
      { description: 'The digit 7 repeats infinitely' },
    ],
    equivalentFractions: ['14/18', '21/27', '28/36', '35/45'],
    asPercentage: '77.78%',
    commonUses: ['Seven ninths of something', 'High proportion', 'Fraction problems'],
    similarFractions: ['5-9', '8-9', '3-4'],
  },
  {
    slug: '8-9',
    numerator: 8,
    denominator: 9,
    fraction: '8/9',
    decimal: '0.888...',
    decimalType: 'repeating',
    repeatEnd: '0.888...',
    percentage: '88.89%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '8 ÷ 9' },
      { description: 'Perform the division', result: '0.888... (repeating)' },
      { description: 'The digit 8 repeats infinitely' },
    ],
    equivalentFractions: ['16/18', '24/27', '32/36', '40/45'],
    asPercentage: '88.89%',
    commonUses: ['Eight ninths of something', 'Nearly complete', 'High percentage calculations'],
    similarFractions: ['7-9', '7-8', '9-10'],
  },
  // Tenths
  {
    slug: '1-10',
    numerator: 1,
    denominator: 10,
    fraction: '1/10',
    decimal: '0.1',
    decimalType: 'terminating',
    percentage: '10%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 10' },
      { description: 'Perform the division', result: '0.1' },
    ],
    equivalentFractions: ['2/20', '3/30', '4/40', '5/50', '10/100'],
    asPercentage: '10%',
    commonUses: ['One tenth of something', '10% in discounts', 'Decimal system base'],
    similarFractions: ['1-5', '1-8', '3-10'],
  },
  {
    slug: '3-10',
    numerator: 3,
    denominator: 10,
    fraction: '3/10',
    decimal: '0.3',
    decimalType: 'terminating',
    percentage: '30%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 10' },
      { description: 'Perform the division', result: '0.3' },
    ],
    equivalentFractions: ['6/20', '9/30', '12/40', '15/50', '30/100'],
    asPercentage: '30%',
    commonUses: ['Three tenths of something', '30% in statistics', 'Decimal conversions'],
    similarFractions: ['1-10', '7-10', '1-3'],
  },
  {
    slug: '7-10',
    numerator: 7,
    denominator: 10,
    fraction: '7/10',
    decimal: '0.7',
    decimalType: 'terminating',
    percentage: '70%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 10' },
      { description: 'Perform the division', result: '0.7' },
    ],
    equivalentFractions: ['14/20', '21/30', '28/40', '35/50', '70/100'],
    asPercentage: '70%',
    commonUses: ['Seven tenths of something', '70% passing grade', 'Majority calculations'],
    similarFractions: ['3-10', '9-10', '3-4'],
  },
  {
    slug: '9-10',
    numerator: 9,
    denominator: 10,
    fraction: '9/10',
    decimal: '0.9',
    decimalType: 'terminating',
    percentage: '90%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '9 ÷ 10' },
      { description: 'Perform the division', result: '0.9' },
    ],
    equivalentFractions: ['18/20', '27/30', '36/40', '45/50', '90/100'],
    asPercentage: '90%',
    commonUses: ['Nine tenths of something', '90% grade (A)', 'High completion rate'],
    similarFractions: ['7-10', '8-9', '19-20'],
  },
  // Twelfths
  {
    slug: '1-12',
    numerator: 1,
    denominator: 12,
    fraction: '1/12',
    decimal: '0.08333...',
    decimalType: 'repeating',
    repeatEnd: '0.08333...',
    percentage: '8.33%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 12' },
      { description: 'Perform the division', result: '0.08333... (repeating)' },
      { description: 'The digit 3 repeats infinitely after 0.08' },
    ],
    equivalentFractions: ['2/24', '3/36', '4/48', '5/60'],
    asPercentage: '8.33%',
    commonUses: ['One twelfth of something', 'Monthly portions (1 month out of 12)', 'Clock divisions (1 hour)'],
    similarFractions: ['1-10', '1-11', '5-12'],
  },
  {
    slug: '5-12',
    numerator: 5,
    denominator: 12,
    fraction: '5/12',
    decimal: '0.41666...',
    decimalType: 'repeating',
    repeatEnd: '0.41666...',
    percentage: '41.67%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 12' },
      { description: 'Perform the division', result: '0.41666... (repeating)' },
      { description: 'The digit 6 repeats infinitely after 0.41' },
    ],
    equivalentFractions: ['10/24', '15/36', '20/48', '25/60'],
    asPercentage: '41.67%',
    commonUses: ['Five twelfths of something', 'Time calculations', 'Monthly divisions'],
    similarFractions: ['1-12', '7-12', '1-2'],
  },
  {
    slug: '7-12',
    numerator: 7,
    denominator: 12,
    fraction: '7/12',
    decimal: '0.58333...',
    decimalType: 'repeating',
    repeatEnd: '0.58333...',
    percentage: '58.33%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 12' },
      { description: 'Perform the division', result: '0.58333... (repeating)' },
      { description: 'The digit 3 repeats infinitely after 0.58' },
    ],
    equivalentFractions: ['14/24', '21/36', '28/48', '35/60'],
    asPercentage: '58.33%',
    commonUses: ['Seven twelfths of something', 'Time periods', 'Majority in twelve parts'],
    similarFractions: ['5-12', '11-12', '3-5'],
  },
  {
    slug: '11-12',
    numerator: 11,
    denominator: 12,
    fraction: '11/12',
    decimal: '0.91666...',
    decimalType: 'repeating',
    repeatEnd: '0.91666...',
    percentage: '91.67%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '11 ÷ 12' },
      { description: 'Perform the division', result: '0.91666... (repeating)' },
      { description: 'The digit 6 repeats infinitely after 0.91' },
    ],
    equivalentFractions: ['22/24', '33/36', '44/48', '55/60'],
    asPercentage: '91.67%',
    commonUses: ['Eleven twelfths of something', 'Nearly complete (11 out of 12 months)', 'High completion rate'],
    similarFractions: ['7-12', '9-10', '15-16'],
  },
  // Sixteenths
  {
    slug: '1-16',
    numerator: 1,
    denominator: 16,
    fraction: '1/16',
    decimal: '0.0625',
    decimalType: 'terminating',
    percentage: '6.25%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 16' },
      { description: 'Perform the division', result: '0.0625' },
    ],
    equivalentFractions: ['2/32', '3/48', '4/64', '5/80'],
    asPercentage: '6.25%',
    commonUses: ['One sixteenth of something', 'Precision measurements in inches', 'Computer binary fractions'],
    similarFractions: ['1-8', '1-32', '3-16'],
  },
  {
    slug: '3-16',
    numerator: 3,
    denominator: 16,
    fraction: '3/16',
    decimal: '0.1875',
    decimalType: 'terminating',
    percentage: '18.75%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 16' },
      { description: 'Perform the division', result: '0.1875' },
    ],
    equivalentFractions: ['6/32', '9/48', '12/64', '15/80'],
    asPercentage: '18.75%',
    commonUses: ['Three sixteenths of something', 'Carpentry measurements', 'Engineering specifications'],
    similarFractions: ['1-16', '5-16', '1-8'],
  },
  {
    slug: '5-16',
    numerator: 5,
    denominator: 16,
    fraction: '5/16',
    decimal: '0.3125',
    decimalType: 'terminating',
    percentage: '31.25%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 16' },
      { description: 'Perform the division', result: '0.3125' },
    ],
    equivalentFractions: ['10/32', '15/48', '20/64', '25/80'],
    asPercentage: '31.25%',
    commonUses: ['Five sixteenths of something', 'Inch measurements', 'Precision tools'],
    similarFractions: ['3-16', '7-16', '1-3'],
  },
  {
    slug: '7-16',
    numerator: 7,
    denominator: 16,
    fraction: '7/16',
    decimal: '0.4375',
    decimalType: 'terminating',
    percentage: '43.75%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 16' },
      { description: 'Perform the division', result: '0.4375' },
    ],
    equivalentFractions: ['14/32', '21/48', '28/64', '35/80'],
    asPercentage: '43.75%',
    commonUses: ['Seven sixteenths of something', 'Construction measurements', 'Manufacturing tolerances'],
    similarFractions: ['5-16', '9-16', '1-2'],
  },
  {
    slug: '9-16',
    numerator: 9,
    denominator: 16,
    fraction: '9/16',
    decimal: '0.5625',
    decimalType: 'terminating',
    percentage: '56.25%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '9 ÷ 16' },
      { description: 'Perform the division', result: '0.5625' },
    ],
    equivalentFractions: ['18/32', '27/48', '36/64', '45/80'],
    asPercentage: '56.25%',
    commonUses: ['Nine sixteenths of something', 'Wrench sizes', 'Drill bit sizes'],
    similarFractions: ['7-16', '11-16', '9-10'],
  },
  {
    slug: '11-16',
    numerator: 11,
    denominator: 16,
    fraction: '11/16',
    decimal: '0.6875',
    decimalType: 'terminating',
    percentage: '68.75%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '11 ÷ 16' },
      { description: 'Perform the division', result: '0.6875' },
    ],
    equivalentFractions: ['22/32', '33/48', '44/64', '55/80'],
    asPercentage: '68.75%',
    commonUses: ['Eleven sixteenths of something', 'Inch measurements', 'Tool sizes'],
    similarFractions: ['9-16', '13-16', '2-3'],
  },
  {
    slug: '13-16',
    numerator: 13,
    denominator: 16,
    fraction: '13/16',
    decimal: '0.8125',
    decimalType: 'terminating',
    percentage: '81.25%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '13 ÷ 16' },
      { description: 'Perform the division', result: '0.8125' },
    ],
    equivalentFractions: ['26/32', '39/48', '52/64', '65/80'],
    asPercentage: '81.25%',
    commonUses: ['Thirteen sixteenths of something', 'Precise measurements', 'Technical specifications'],
    similarFractions: ['11-16', '15-16', '4-5'],
  },
  {
    slug: '15-16',
    numerator: 15,
    denominator: 16,
    fraction: '15/16',
    decimal: '0.9375',
    decimalType: 'terminating',
    percentage: '93.75%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '15 ÷ 16' },
      { description: 'Perform the division', result: '0.9375' },
    ],
    equivalentFractions: ['30/32', '45/48', '60/64', '75/80'],
    asPercentage: '93.75%',
    commonUses: ['Fifteen sixteenths of something', 'Nearly complete measurement', 'High precision work'],
    similarFractions: ['13-16', '7-8', '31-32'],
  },
  // Additional common fractions
  {
    slug: '1-11',
    numerator: 1,
    denominator: 11,
    fraction: '1/11',
    decimal: '0.090909...',
    decimalType: 'repeating',
    repeatEnd: '0.090909...',
    percentage: '9.09%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 11' },
      { description: 'Perform the division', result: '0.090909... (repeating)' },
      { description: 'The sequence 09 repeats infinitely' },
    ],
    equivalentFractions: ['2/22', '3/33', '4/44', '5/55'],
    asPercentage: '9.09%',
    commonUses: ['One eleventh of something', 'Dividing into 11 equal parts', 'Mathematical calculations'],
    similarFractions: ['1-10', '1-12', '1-9'],
  },
  {
    slug: '1-15',
    numerator: 1,
    denominator: 15,
    fraction: '1/15',
    decimal: '0.0666...',
    decimalType: 'repeating',
    repeatEnd: '0.0666...',
    percentage: '6.67%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 15' },
      { description: 'Perform the division', result: '0.0666... (repeating)' },
      { description: 'The digit 6 repeats infinitely after 0.0' },
    ],
    equivalentFractions: ['2/30', '3/45', '4/60', '5/75'],
    asPercentage: '6.67%',
    commonUses: ['One fifteenth of something', 'Dividing into 15 parts', 'Fraction problems'],
    similarFractions: ['1-16', '1-14', '1-12'],
  },
  {
    slug: '2-15',
    numerator: 2,
    denominator: 15,
    fraction: '2/15',
    decimal: '0.1333...',
    decimalType: 'repeating',
    repeatEnd: '0.1333...',
    percentage: '13.33%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 15' },
      { description: 'Perform the division', result: '0.1333... (repeating)' },
      { description: 'The digit 3 repeats infinitely after 0.1' },
    ],
    equivalentFractions: ['4/30', '6/45', '8/60', '10/75'],
    asPercentage: '13.33%',
    commonUses: ['Two fifteenths of something', 'Fraction arithmetic', 'Division problems'],
    similarFractions: ['1-15', '1-7', '1-8'],
  },
  {
    slug: '1-20',
    numerator: 1,
    denominator: 20,
    fraction: '1/20',
    decimal: '0.05',
    decimalType: 'terminating',
    percentage: '5%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 20' },
      { description: 'Perform the division', result: '0.05' },
    ],
    equivalentFractions: ['2/40', '3/60', '4/80', '5/100'],
    asPercentage: '5%',
    commonUses: ['One twentieth of something', '5% (common discount rate)', 'Statistics and probability'],
    similarFractions: ['1-10', '1-25', '3-20'],
  },
  {
    slug: '3-20',
    numerator: 3,
    denominator: 20,
    fraction: '3/20',
    decimal: '0.15',
    decimalType: 'terminating',
    percentage: '15%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 20' },
      { description: 'Perform the division', result: '0.15' },
    ],
    equivalentFractions: ['6/40', '9/60', '12/80', '15/100'],
    asPercentage: '15%',
    commonUses: ['Three twentieths of something', '15% (common tip rate)', 'Percentage calculations'],
    similarFractions: ['1-20', '7-20', '1-5'],
  },
  {
    slug: '7-20',
    numerator: 7,
    denominator: 20,
    fraction: '7/20',
    decimal: '0.35',
    decimalType: 'terminating',
    percentage: '35%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 20' },
      { description: 'Perform the division', result: '0.35' },
    ],
    equivalentFractions: ['14/40', '21/60', '28/80', '35/100'],
    asPercentage: '35%',
    commonUses: ['Seven twentieths of something', '35% in statistics', 'Proportions'],
    similarFractions: ['3-20', '9-20', '1-3'],
  },
  {
    slug: '9-20',
    numerator: 9,
    denominator: 20,
    fraction: '9/20',
    decimal: '0.45',
    decimalType: 'terminating',
    percentage: '45%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '9 ÷ 20' },
      { description: 'Perform the division', result: '0.45' },
    ],
    equivalentFractions: ['18/40', '27/60', '36/80', '45/100'],
    asPercentage: '45%',
    commonUses: ['Nine twentieths of something', '45% in surveys', 'Nearly half'],
    similarFractions: ['7-20', '11-20', '1-2'],
  },
  {
    slug: '11-20',
    numerator: 11,
    denominator: 20,
    fraction: '11/20',
    decimal: '0.55',
    decimalType: 'terminating',
    percentage: '55%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '11 ÷ 20' },
      { description: 'Perform the division', result: '0.55' },
    ],
    equivalentFractions: ['22/40', '33/60', '44/80', '55/100'],
    asPercentage: '55%',
    commonUses: ['Eleven twentieths of something', '55% majority', 'Just over half'],
    similarFractions: ['9-20', '13-20', '3-5'],
  },
  {
    slug: '13-20',
    numerator: 13,
    denominator: 20,
    fraction: '13/20',
    decimal: '0.65',
    decimalType: 'terminating',
    percentage: '65%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '13 ÷ 20' },
      { description: 'Perform the division', result: '0.65' },
    ],
    equivalentFractions: ['26/40', '39/60', '52/80', '65/100'],
    asPercentage: '65%',
    commonUses: ['Thirteen twentieths of something', '65% passing grade', 'Statistical analysis'],
    similarFractions: ['11-20', '17-20', '2-3'],
  },
  {
    slug: '17-20',
    numerator: 17,
    denominator: 20,
    fraction: '17/20',
    decimal: '0.85',
    decimalType: 'terminating',
    percentage: '85%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '17 ÷ 20' },
      { description: 'Perform the division', result: '0.85' },
    ],
    equivalentFractions: ['34/40', '51/60', '68/80', '85/100'],
    asPercentage: '85%',
    commonUses: ['Seventeen twentieths of something', '85% grade (B)', 'High completion rate'],
    similarFractions: ['13-20', '19-20', '4-5'],
  },
  {
    slug: '19-20',
    numerator: 19,
    denominator: 20,
    fraction: '19/20',
    decimal: '0.95',
    decimalType: 'terminating',
    percentage: '95%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '19 ÷ 20' },
      { description: 'Perform the division', result: '0.95' },
    ],
    equivalentFractions: ['38/40', '57/60', '76/80', '95/100'],
    asPercentage: '95%',
    commonUses: ['Nineteen twentieths of something', '95% confidence level', 'Nearly complete'],
    similarFractions: ['17-20', '9-10', '39-40'],
  },
  {
    slug: '1-25',
    numerator: 1,
    denominator: 25,
    fraction: '1/25',
    decimal: '0.04',
    decimalType: 'terminating',
    percentage: '4%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 25' },
      { description: 'Perform the division', result: '0.04' },
    ],
    equivalentFractions: ['2/50', '3/75', '4/100', '8/200'],
    asPercentage: '4%',
    commonUses: ['One twenty-fifth of something', '4% interest rate', 'Small percentages'],
    similarFractions: ['1-20', '1-50', '1-100'],
  },
  {
    slug: '3-25',
    numerator: 3,
    denominator: 25,
    fraction: '3/25',
    decimal: '0.12',
    decimalType: 'terminating',
    percentage: '12%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 25' },
      { description: 'Perform the division', result: '0.12' },
    ],
    equivalentFractions: ['6/50', '9/75', '12/100', '24/200'],
    asPercentage: '12%',
    commonUses: ['Three twenty-fifths of something', '12% rate', 'Percentage calculations'],
    similarFractions: ['1-25', '1-8', '1-10'],
  },
  {
    slug: '7-25',
    numerator: 7,
    denominator: 25,
    fraction: '7/25',
    decimal: '0.28',
    decimalType: 'terminating',
    percentage: '28%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 25' },
      { description: 'Perform the division', result: '0.28' },
    ],
    equivalentFractions: ['14/50', '21/75', '28/100', '56/200'],
    asPercentage: '28%',
    commonUses: ['Seven twenty-fifths of something', '28% in surveys', 'Statistical data'],
    similarFractions: ['3-25', '3-10', '1-4'],
  },
  {
    slug: '9-25',
    numerator: 9,
    denominator: 25,
    fraction: '9/25',
    decimal: '0.36',
    decimalType: 'terminating',
    percentage: '36%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '9 ÷ 25' },
      { description: 'Perform the division', result: '0.36' },
    ],
    equivalentFractions: ['18/50', '27/75', '36/100', '72/200'],
    asPercentage: '36%',
    commonUses: ['Nine twenty-fifths of something', '36% in statistics', 'Proportional calculations'],
    similarFractions: ['7-25', '11-25', '2-5'],
  },
  {
    slug: '11-25',
    numerator: 11,
    denominator: 25,
    fraction: '11/25',
    decimal: '0.44',
    decimalType: 'terminating',
    percentage: '44%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '11 ÷ 25' },
      { description: 'Perform the division', result: '0.44' },
    ],
    equivalentFractions: ['22/50', '33/75', '44/100', '88/200'],
    asPercentage: '44%',
    commonUses: ['Eleven twenty-fifths of something', '44% in polls', 'Nearly half'],
    similarFractions: ['9-25', '13-25', '1-2'],
  },
  {
    slug: '13-25',
    numerator: 13,
    denominator: 25,
    fraction: '13/25',
    decimal: '0.52',
    decimalType: 'terminating',
    percentage: '52%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '13 ÷ 25' },
      { description: 'Perform the division', result: '0.52' },
    ],
    equivalentFractions: ['26/50', '39/75', '52/100', '104/200'],
    asPercentage: '52%',
    commonUses: ['Thirteen twenty-fifths of something', '52% majority', 'Just over half'],
    similarFractions: ['11-25', '17-25', '1-2'],
  },
  {
    slug: '17-25',
    numerator: 17,
    denominator: 25,
    fraction: '17/25',
    decimal: '0.68',
    decimalType: 'terminating',
    percentage: '68%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '17 ÷ 25' },
      { description: 'Perform the division', result: '0.68' },
    ],
    equivalentFractions: ['34/50', '51/75', '68/100', '136/200'],
    asPercentage: '68%',
    commonUses: ['Seventeen twenty-fifths of something', '68% in surveys', 'Statistical majority'],
    similarFractions: ['13-25', '19-25', '2-3'],
  },
  {
    slug: '19-25',
    numerator: 19,
    denominator: 25,
    fraction: '19/25',
    decimal: '0.76',
    decimalType: 'terminating',
    percentage: '76%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '19 ÷ 25' },
      { description: 'Perform the division', result: '0.76' },
    ],
    equivalentFractions: ['38/50', '57/75', '76/100', '152/200'],
    asPercentage: '76%',
    commonUses: ['Nineteen twenty-fifths of something', '76% in grading', 'High proportion'],
    similarFractions: ['17-25', '21-25', '3-4'],
  },
  {
    slug: '21-25',
    numerator: 21,
    denominator: 25,
    fraction: '21/25',
    decimal: '0.84',
    decimalType: 'terminating',
    percentage: '84%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '21 ÷ 25' },
      { description: 'Perform the division', result: '0.84' },
    ],
    equivalentFractions: ['42/50', '63/75', '84/100', '168/200'],
    asPercentage: '84%',
    commonUses: ['Twenty-one twenty-fifths of something', '84% grade (B)', 'High completion'],
    similarFractions: ['19-25', '23-25', '4-5'],
  },
  {
    slug: '23-25',
    numerator: 23,
    denominator: 25,
    fraction: '23/25',
    decimal: '0.92',
    decimalType: 'terminating',
    percentage: '92%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '23 ÷ 25' },
      { description: 'Perform the division', result: '0.92' },
    ],
    equivalentFractions: ['46/50', '69/75', '92/100', '184/200'],
    asPercentage: '92%',
    commonUses: ['Twenty-three twenty-fifths of something', '92% grade (A)', 'Nearly complete'],
    similarFractions: ['21-25', '9-10', '24-25'],
  },
  {
    slug: '24-25',
    numerator: 24,
    denominator: 25,
    fraction: '24/25',
    decimal: '0.96',
    decimalType: 'terminating',
    percentage: '96%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '24 ÷ 25' },
      { description: 'Perform the division', result: '0.96' },
    ],
    equivalentFractions: ['48/50', '72/75', '96/100', '192/200'],
    asPercentage: '96%',
    commonUses: ['Twenty-four twenty-fifths of something', '96% success rate', 'Very high percentage'],
    similarFractions: ['23-25', '19-20', '49-50'],
  },
  {
    slug: '1-32',
    numerator: 1,
    denominator: 32,
    fraction: '1/32',
    decimal: '0.03125',
    decimalType: 'terminating',
    percentage: '3.125%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 32' },
      { description: 'Perform the division', result: '0.03125' },
    ],
    equivalentFractions: ['2/64', '3/96', '4/128', '5/160'],
    asPercentage: '3.125%',
    commonUses: ['One thirty-second of something', 'Very precise measurements', 'Binary fractions in computing'],
    similarFractions: ['1-16', '1-64', '3-32'],
  },
  {
    slug: '3-32',
    numerator: 3,
    denominator: 32,
    fraction: '3/32',
    decimal: '0.09375',
    decimalType: 'terminating',
    percentage: '9.375%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 32' },
      { description: 'Perform the division', result: '0.09375' },
    ],
    equivalentFractions: ['6/64', '9/96', '12/128', '15/160'],
    asPercentage: '9.375%',
    commonUses: ['Three thirty-seconds of something', 'Precision engineering', 'Fine measurements'],
    similarFractions: ['1-32', '5-32', '1-10'],
  },
  {
    slug: '5-32',
    numerator: 5,
    denominator: 32,
    fraction: '5/32',
    decimal: '0.15625',
    decimalType: 'terminating',
    percentage: '15.625%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 32' },
      { description: 'Perform the division', result: '0.15625' },
    ],
    equivalentFractions: ['10/64', '15/96', '20/128', '25/160'],
    asPercentage: '15.625%',
    commonUses: ['Five thirty-seconds of something', 'Drill bit sizes', 'Machine shop work'],
    similarFractions: ['3-32', '7-32', '1-6'],
  },
  {
    slug: '7-32',
    numerator: 7,
    denominator: 32,
    fraction: '7/32',
    decimal: '0.21875',
    decimalType: 'terminating',
    percentage: '21.875%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '7 ÷ 32' },
      { description: 'Perform the division', result: '0.21875' },
    ],
    equivalentFractions: ['14/64', '21/96', '28/128', '35/160'],
    asPercentage: '21.875%',
    commonUses: ['Seven thirty-seconds of something', 'Tool measurements', 'Precision work'],
    similarFractions: ['5-32', '9-32', '1-4'],
  },
  {
    slug: '9-32',
    numerator: 9,
    denominator: 32,
    fraction: '9/32',
    decimal: '0.28125',
    decimalType: 'terminating',
    percentage: '28.125%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '9 ÷ 32' },
      { description: 'Perform the division', result: '0.28125' },
    ],
    equivalentFractions: ['18/64', '27/96', '36/128', '45/160'],
    asPercentage: '28.125%',
    commonUses: ['Nine thirty-seconds of something', 'Technical specifications', 'Measurement conversions'],
    similarFractions: ['7-32', '11-32', '1-3'],
  },
  {
    slug: '11-32',
    numerator: 11,
    denominator: 32,
    fraction: '11/32',
    decimal: '0.34375',
    decimalType: 'terminating',
    percentage: '34.375%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '11 ÷ 32' },
      { description: 'Perform the division', result: '0.34375' },
    ],
    equivalentFractions: ['22/64', '33/96', '44/128', '55/160'],
    asPercentage: '34.375%',
    commonUses: ['Eleven thirty-seconds of something', 'Wrench sizes', 'Engineering measurements'],
    similarFractions: ['9-32', '13-32', '1-3'],
  },
  {
    slug: '13-32',
    numerator: 13,
    denominator: 32,
    fraction: '13/32',
    decimal: '0.40625',
    decimalType: 'terminating',
    percentage: '40.625%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '13 ÷ 32' },
      { description: 'Perform the division', result: '0.40625' },
    ],
    equivalentFractions: ['26/64', '39/96', '52/128', '65/160'],
    asPercentage: '40.625%',
    commonUses: ['Thirteen thirty-seconds of something', 'Socket sizes', 'Mechanical measurements'],
    similarFractions: ['11-32', '15-32', '2-5'],
  },
  {
    slug: '15-32',
    numerator: 15,
    denominator: 32,
    fraction: '15/32',
    decimal: '0.46875',
    decimalType: 'terminating',
    percentage: '46.875%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '15 ÷ 32' },
      { description: 'Perform the division', result: '0.46875' },
    ],
    equivalentFractions: ['30/64', '45/96', '60/128', '75/160'],
    asPercentage: '46.875%',
    commonUses: ['Fifteen thirty-seconds of something', 'Nearly half', 'Precision tools'],
    similarFractions: ['13-32', '1-2', '17-32'],
  },
  {
    slug: '1-50',
    numerator: 1,
    denominator: 50,
    fraction: '1/50',
    decimal: '0.02',
    decimalType: 'terminating',
    percentage: '2%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 50' },
      { description: 'Perform the division', result: '0.02' },
    ],
    equivalentFractions: ['2/100', '3/150', '4/200', '5/250'],
    asPercentage: '2%',
    commonUses: ['One fiftieth of something', '2% interest rate', 'Small percentages'],
    similarFractions: ['1-25', '1-100', '1-20'],
  },
  {
    slug: '1-100',
    numerator: 1,
    denominator: 100,
    fraction: '1/100',
    decimal: '0.01',
    decimalType: 'terminating',
    percentage: '1%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 100' },
      { description: 'Perform the division', result: '0.01' },
    ],
    equivalentFractions: ['2/200', '3/300', '4/400', '5/500'],
    asPercentage: '1%',
    commonUses: ['One hundredth of something', '1% (one percent)', 'Percentages and decimals'],
    similarFractions: ['1-50', '1-25', '1-10'],
  },
  {
    slug: '2-7',
    numerator: 2,
    denominator: 7,
    fraction: '2/7',
    decimal: '0.285714...',
    decimalType: 'repeating',
    repeatEnd: '0.285714...',
    percentage: '28.57%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 7' },
      { description: 'Perform the division', result: '0.285714... (repeating)' },
      { description: 'The sequence 285714 repeats infinitely' },
    ],
    equivalentFractions: ['4/14', '6/21', '8/28', '10/35'],
    asPercentage: '28.57%',
    commonUses: ['Two sevenths of something', 'Weekly calculations', 'Division problems'],
    similarFractions: ['1-7', '3-7', '1-4'],
  },
  {
    slug: '3-7',
    numerator: 3,
    denominator: 7,
    fraction: '3/7',
    decimal: '0.428571...',
    decimalType: 'repeating',
    repeatEnd: '0.428571...',
    percentage: '42.86%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 7' },
      { description: 'Perform the division', result: '0.428571... (repeating)' },
      { description: 'The sequence 428571 repeats infinitely' },
    ],
    equivalentFractions: ['6/14', '9/21', '12/28', '15/35'],
    asPercentage: '42.86%',
    commonUses: ['Three sevenths of something', 'Fraction calculations', 'Mathematical problems'],
    similarFractions: ['2-7', '4-7', '1-2'],
  },
  {
    slug: '4-7',
    numerator: 4,
    denominator: 7,
    fraction: '4/7',
    decimal: '0.571428...',
    decimalType: 'repeating',
    repeatEnd: '0.571428...',
    percentage: '57.14%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '4 ÷ 7' },
      { description: 'Perform the division', result: '0.571428... (repeating)' },
      { description: 'The sequence 571428 repeats infinitely' },
    ],
    equivalentFractions: ['8/14', '12/21', '16/28', '20/35'],
    asPercentage: '57.14%',
    commonUses: ['Four sevenths of something', 'Majority in sevenths', 'Mathematical operations'],
    similarFractions: ['3-7', '5-7', '4-5'],
  },
  {
    slug: '5-7',
    numerator: 5,
    denominator: 7,
    fraction: '5/7',
    decimal: '0.714285...',
    decimalType: 'repeating',
    repeatEnd: '0.714285...',
    percentage: '71.43%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '5 ÷ 7' },
      { description: 'Perform the division', result: '0.714285... (repeating)' },
      { description: 'The sequence 714285 repeats infinitely' },
    ],
    equivalentFractions: ['10/14', '15/21', '20/28', '25/35'],
    asPercentage: '71.43%',
    commonUses: ['Five sevenths of something', 'High proportion', 'Fraction problems'],
    similarFractions: ['4-7', '6-7', '3-4'],
  },
  {
    slug: '6-7',
    numerator: 6,
    denominator: 7,
    fraction: '6/7',
    decimal: '0.857142...',
    decimalType: 'repeating',
    repeatEnd: '0.857142...',
    percentage: '85.71%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '6 ÷ 7' },
      { description: 'Perform the division', result: '0.857142... (repeating)' },
      { description: 'The sequence 857142 repeats infinitely' },
    ],
    equivalentFractions: ['12/14', '18/21', '24/28', '30/35'],
    asPercentage: '85.71%',
    commonUses: ['Six sevenths of something', 'Nearly complete (6 out of 7 days)', 'High percentage'],
    similarFractions: ['5-7', '7-8', '5-6'],
  },
  {
    slug: '2-11',
    numerator: 2,
    denominator: 11,
    fraction: '2/11',
    decimal: '0.181818...',
    decimalType: 'repeating',
    repeatEnd: '0.181818...',
    percentage: '18.18%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 11' },
      { description: 'Perform the division', result: '0.181818... (repeating)' },
      { description: 'The sequence 18 repeats infinitely' },
    ],
    equivalentFractions: ['4/22', '6/33', '8/44', '10/55'],
    asPercentage: '18.18%',
    commonUses: ['Two elevenths of something', 'Fraction arithmetic', 'Division calculations'],
    similarFractions: ['1-11', '3-11', '1-5'],
  },
  {
    slug: '3-11',
    numerator: 3,
    denominator: 11,
    fraction: '3/11',
    decimal: '0.272727...',
    decimalType: 'repeating',
    repeatEnd: '0.272727...',
    percentage: '27.27%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 11' },
      { description: 'Perform the division', result: '0.272727... (repeating)' },
      { description: 'The sequence 27 repeats infinitely' },
    ],
    equivalentFractions: ['6/22', '9/33', '12/44', '15/55'],
    asPercentage: '27.27%',
    commonUses: ['Three elevenths of something', 'Mathematical operations', 'Fraction problems'],
    similarFractions: ['2-11', '4-11', '1-4'],
  },
  {
    slug: '17-32',
    numerator: 17,
    denominator: 32,
    fraction: '17/32',
    decimal: '0.53125',
    decimalType: 'terminating',
    percentage: '53.125%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '17 ÷ 32' },
      { description: 'Perform the division', result: '0.53125' },
    ],
    equivalentFractions: ['34/64', '51/96', '68/128', '85/160'],
    asPercentage: '53.125%',
    commonUses: ['Seventeen thirty-seconds of something', 'Precision measurements', 'Technical work'],
    similarFractions: ['15-32', '1-2', '19-32'],
  },
  {
    slug: '19-32',
    numerator: 19,
    denominator: 32,
    fraction: '19/32',
    decimal: '0.59375',
    decimalType: 'terminating',
    percentage: '59.375%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '19 ÷ 32' },
      { description: 'Perform the division', result: '0.59375' },
    ],
    equivalentFractions: ['38/64', '57/96', '76/128', '95/160'],
    asPercentage: '59.375%',
    commonUses: ['Nineteen thirty-seconds of something', 'Engineering specs', 'Measurement conversions'],
    similarFractions: ['17-32', '21-32', '3-5'],
  },
  {
    slug: '21-32',
    numerator: 21,
    denominator: 32,
    fraction: '21/32',
    decimal: '0.65625',
    decimalType: 'terminating',
    percentage: '65.625%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '21 ÷ 32' },
      { description: 'Perform the division', result: '0.65625' },
    ],
    equivalentFractions: ['42/64', '63/96', '84/128', '105/160'],
    asPercentage: '65.625%',
    commonUses: ['Twenty-one thirty-seconds of something', 'Precision tools', 'Manufacturing'],
    similarFractions: ['19-32', '23-32', '2-3'],
  },
  {
    slug: '23-32',
    numerator: 23,
    denominator: 32,
    fraction: '23/32',
    decimal: '0.71875',
    decimalType: 'terminating',
    percentage: '71.875%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '23 ÷ 32' },
      { description: 'Perform the division', result: '0.71875' },
    ],
    equivalentFractions: ['46/64', '69/96', '92/128', '115/160'],
    asPercentage: '71.875%',
    commonUses: ['Twenty-three thirty-seconds of something', 'Drill bit sizes', 'Technical measurements'],
    similarFractions: ['21-32', '25-32', '3-4'],
  },
  {
    slug: '25-32',
    numerator: 25,
    denominator: 32,
    fraction: '25/32',
    decimal: '0.78125',
    decimalType: 'terminating',
    percentage: '78.125%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '25 ÷ 32' },
      { description: 'Perform the division', result: '0.78125' },
    ],
    equivalentFractions: ['50/64', '75/96', '100/128', '125/160'],
    asPercentage: '78.125%',
    commonUses: ['Twenty-five thirty-seconds of something', 'Carpentry work', 'Tool sizes'],
    similarFractions: ['23-32', '27-32', '3-4'],
  },
  {
    slug: '27-32',
    numerator: 27,
    denominator: 32,
    fraction: '27/32',
    decimal: '0.84375',
    decimalType: 'terminating',
    percentage: '84.375%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '27 ÷ 32' },
      { description: 'Perform the division', result: '0.84375' },
    ],
    equivalentFractions: ['54/64', '81/96', '108/128', '135/160'],
    asPercentage: '84.375%',
    commonUses: ['Twenty-seven thirty-seconds of something', 'Precision engineering', 'Fine measurements'],
    similarFractions: ['25-32', '29-32', '7-8'],
  },
  {
    slug: '29-32',
    numerator: 29,
    denominator: 32,
    fraction: '29/32',
    decimal: '0.90625',
    decimalType: 'terminating',
    percentage: '90.625%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '29 ÷ 32' },
      { description: 'Perform the division', result: '0.90625' },
    ],
    equivalentFractions: ['58/64', '87/96', '116/128', '145/160'],
    asPercentage: '90.625%',
    commonUses: ['Twenty-nine thirty-seconds of something', 'Nearly complete measurement', 'High precision work'],
    similarFractions: ['27-32', '31-32', '15-16'],
  },
  {
    slug: '31-32',
    numerator: 31,
    denominator: 32,
    fraction: '31/32',
    decimal: '0.96875',
    decimalType: 'terminating',
    percentage: '96.875%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '31 ÷ 32' },
      { description: 'Perform the division', result: '0.96875' },
    ],
    equivalentFractions: ['62/64', '93/96', '124/128', '155/160'],
    asPercentage: '96.875%',
    commonUses: ['Thirty-one thirty-seconds of something', 'Nearly complete', 'Very high precision'],
    similarFractions: ['29-32', '15-16', '63-64'],
  },
  {
    slug: '1-13',
    numerator: 1,
    denominator: 13,
    fraction: '1/13',
    decimal: '0.076923...',
    decimalType: 'repeating',
    repeatEnd: '0.076923...',
    percentage: '7.69%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 13' },
      { description: 'Perform the division', result: '0.076923... (repeating)' },
      { description: 'The sequence 076923 repeats infinitely' },
    ],
    equivalentFractions: ['2/26', '3/39', '4/52', '5/65'],
    asPercentage: '7.69%',
    commonUses: ['One thirteenth of something', 'Division into 13 parts', 'Mathematical calculations'],
    similarFractions: ['1-12', '1-14', '1-15'],
  },
  {
    slug: '1-14',
    numerator: 1,
    denominator: 14,
    fraction: '1/14',
    decimal: '0.071428...',
    decimalType: 'repeating',
    repeatEnd: '0.071428...',
    percentage: '7.14%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '1 ÷ 14' },
      { description: 'Perform the division', result: '0.071428... (repeating)' },
      { description: 'The sequence 071428 repeats infinitely' },
    ],
    equivalentFractions: ['2/28', '3/42', '4/56', '5/70'],
    asPercentage: '7.14%',
    commonUses: ['One fourteenth of something', 'Bi-weekly calculations', 'Fraction problems'],
    similarFractions: ['1-13', '1-15', '1-7'],
  },
  {
    slug: '2-25',
    numerator: 2,
    denominator: 25,
    fraction: '2/25',
    decimal: '0.08',
    decimalType: 'terminating',
    percentage: '8%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '2 ÷ 25' },
      { description: 'Perform the division', result: '0.08' },
    ],
    equivalentFractions: ['4/50', '6/75', '8/100', '16/200'],
    asPercentage: '8%',
    commonUses: ['Two twenty-fifths of something', '8% rate', 'Percentage calculations'],
    similarFractions: ['1-25', '3-25', '1-10'],
  },
  {
    slug: '4-25',
    numerator: 4,
    denominator: 25,
    fraction: '4/25',
    decimal: '0.16',
    decimalType: 'terminating',
    percentage: '16%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '4 ÷ 25' },
      { description: 'Perform the division', result: '0.16' },
    ],
    equivalentFractions: ['8/50', '12/75', '16/100', '32/200'],
    asPercentage: '16%',
    commonUses: ['Four twenty-fifths of something', '16% in statistics', 'Proportional calculations'],
    similarFractions: ['3-25', '1-6', '1-5'],
  },
  {
    slug: '6-25',
    numerator: 6,
    denominator: 25,
    fraction: '6/25',
    decimal: '0.24',
    decimalType: 'terminating',
    percentage: '24%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '6 ÷ 25' },
      { description: 'Perform the division', result: '0.24' },
    ],
    equivalentFractions: ['12/50', '18/75', '24/100', '48/200'],
    asPercentage: '24%',
    commonUses: ['Six twenty-fifths of something', '24% rate', 'Statistical analysis'],
    similarFractions: ['1-4', '3-25', '7-25'],
  },
  {
    slug: '8-25',
    numerator: 8,
    denominator: 25,
    fraction: '8/25',
    decimal: '0.32',
    decimalType: 'terminating',
    percentage: '32%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '8 ÷ 25' },
      { description: 'Perform the division', result: '0.32' },
    ],
    equivalentFractions: ['16/50', '24/75', '32/100', '64/200'],
    asPercentage: '32%',
    commonUses: ['Eight twenty-fifths of something', '32% in polls', 'Percentage work'],
    similarFractions: ['7-25', '9-25', '1-3'],
  },
  {
    slug: '12-25',
    numerator: 12,
    denominator: 25,
    fraction: '12/25',
    decimal: '0.48',
    decimalType: 'terminating',
    percentage: '48%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '12 ÷ 25' },
      { description: 'Perform the division', result: '0.48' },
    ],
    equivalentFractions: ['24/50', '36/75', '48/100', '96/200'],
    asPercentage: '48%',
    commonUses: ['Twelve twenty-fifths of something', '48% in surveys', 'Nearly half'],
    similarFractions: ['11-25', '13-25', '1-2'],
  },
  {
    slug: '14-25',
    numerator: 14,
    denominator: 25,
    fraction: '14/25',
    decimal: '0.56',
    decimalType: 'terminating',
    percentage: '56%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '14 ÷ 25' },
      { description: 'Perform the division', result: '0.56' },
    ],
    equivalentFractions: ['28/50', '42/75', '56/100', '112/200'],
    asPercentage: '56%',
    commonUses: ['Fourteen twenty-fifths of something', '56% majority', 'Just over half'],
    similarFractions: ['13-25', '3-5', '17-25'],
  },
  {
    slug: '16-25',
    numerator: 16,
    denominator: 25,
    fraction: '16/25',
    decimal: '0.64',
    decimalType: 'terminating',
    percentage: '64%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '16 ÷ 25' },
      { description: 'Perform the division', result: '0.64' },
    ],
    equivalentFractions: ['32/50', '48/75', '64/100', '128/200'],
    asPercentage: '64%',
    commonUses: ['Sixteen twenty-fifths of something', '64% in statistics', 'High proportion'],
    similarFractions: ['17-25', '3-5', '13-20'],
  },
  {
    slug: '18-25',
    numerator: 18,
    denominator: 25,
    fraction: '18/25',
    decimal: '0.72',
    decimalType: 'terminating',
    percentage: '72%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '18 ÷ 25' },
      { description: 'Perform the division', result: '0.72' },
    ],
    equivalentFractions: ['36/50', '54/75', '72/100', '144/200'],
    asPercentage: '72%',
    commonUses: ['Eighteen twenty-fifths of something', '72% passing grade', 'High completion'],
    similarFractions: ['17-25', '19-25', '3-4'],
  },
  {
    slug: '22-25',
    numerator: 22,
    denominator: 25,
    fraction: '22/25',
    decimal: '0.88',
    decimalType: 'terminating',
    percentage: '88%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '22 ÷ 25' },
      { description: 'Perform the division', result: '0.88' },
    ],
    equivalentFractions: ['44/50', '66/75', '88/100', '176/200'],
    asPercentage: '88%',
    commonUses: ['Twenty-two twenty-fifths of something', '88% grade (B+)', 'High success rate'],
    similarFractions: ['21-25', '23-25', '7-8'],
  },
  {
    slug: '3-13',
    numerator: 3,
    denominator: 13,
    fraction: '3/13',
    decimal: '0.230769...',
    decimalType: 'repeating',
    repeatEnd: '0.230769...',
    percentage: '23.08%',
    steps: [
      { description: 'Divide the numerator by the denominator', calculation: '3 ÷ 13' },
      { description: 'Perform the division', result: '0.230769... (repeating)' },
      { description: 'The sequence 230769 repeats infinitely' },
    ],
    equivalentFractions: ['6/26', '9/39', '12/52', '15/65'],
    asPercentage: '23.08%',
    commonUses: ['Three thirteenths of something', 'Fraction arithmetic', 'Mathematical problems'],
    similarFractions: ['1-13', '1-4', '2-9'],
  },
];

// Helper function to get fraction by slug
export function getFractionBySlug(slug: string): FractionData | undefined {
  return fractionsData.find(f => f.slug === slug);
}

// Helper function to get all fraction slugs (for sitemap and static generation)
export function getAllFractionSlugs(): string[] {
  return fractionsData.map(f => f.slug);
}

// Helper function to convert fraction notation to slug
export function fractionToSlug(numerator: number, denominator: number): string {
  return `${numerator}-${denominator}`;
}

// Helper function to parse slug back to fraction
export function slugToFraction(slug: string): { numerator: number; denominator: number } | null {
  const parts = slug.split('-');
  if (parts.length === 2) {
    const numerator = parseInt(parts[0]);
    const denominator = parseInt(parts[1]);
    if (!isNaN(numerator) && !isNaN(denominator)) {
      return { numerator, denominator };
    }
  }
  return null;
}
