import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Scientific Notation Converter - Convert to Standard, E-notation & Engineering Form | The Tutor Bridge',
  description: 'Free scientific notation converter to convert numbers between scientific notation, standard form, e-notation, engineering notation, and word form. Get step-by-step conversions with order of magnitude.',
  keywords: [
    'scientific notation converter',
    'scientific notation calculator',
    'convert to scientific notation',
    'scientific notation to standard form',
    'standard form to scientific notation',
    'e notation converter',
    'engineering notation converter',
    'scientific notation to decimal',
    'decimal to scientific notation',
    'scientific notation to number',
    'number to scientific notation',
    'exponential notation converter',
    'scientific notation tool',
    'scientific notation online',
    'free scientific notation calculator',
    'scientific notation with steps',
    'how to convert scientific notation',
    'scientific notation examples',
    'scientific e notation',
    'scientific notation format',
    'convert scientific notation to real number',
    'scientific notation word form',
    'order of magnitude calculator',
    'scientific notation explained',
    'standard form calculator',
    'exponential form converter',
    'powers of 10 calculator',
    'scientific notation practice',
    'scientific notation helper',
    'scientific notation solver',
    'scientific notation translator',
    'number to e notation',
    'e notation to decimal',
    'engineering notation calculator',
    'engineering form converter',
    'scientific notation to engineering notation',
    'significant figures scientific notation',
    'mantissa and exponent',
    'scientific notation parts',
    'coefficient and exponent',
    'base 10 notation',
    'scientific notation prefix',
    'giga mega kilo notation',
    'metric prefix converter',
    'scientific notation to words',
    'number word form',
    'billion trillion notation',
    'large number converter',
    'small number scientific notation',
    'very large numbers',
    'very small numbers',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/scientific-notation-converter',
  },
  openGraph: {
    title: 'Scientific Notation Converter - Convert to Standard & E-notation',
    description: 'Free scientific notation converter with step-by-step conversions. Convert between scientific notation, standard form, e-notation, engineering notation, and word form instantly.',
    url: 'https://www.thetutorbridge.com/calculators/scientific-notation-converter',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Scientific Notation Converter - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Scientific Notation Converter - Free Tool',
    description: 'Convert numbers between scientific notation, standard form, e-notation, and engineering notation with detailed explanations.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function ScientificNotationConverterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
