import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'BMI Calculator - Free Body Mass Index Calculator for Adults & Children | The Tutor Bridge',
  description: 'Free BMI calculator for adults and children. Calculate your Body Mass Index using metric or imperial units. Get BMI classification, healthy weight range, and comprehensive health insights.',
  keywords: [
    'bmi calculator',
    'body mass index calculator',
    'calculate bmi',
    'bmi calculator for adults',
    'bmi calculator for children',
    'free bmi calculator',
    'online bmi calculator',
    'bmi formula',
    'how to calculate bmi',
    'body mass index',
    'bmi chart',
    'bmi calculator metric',
    'bmi calculator imperial',
    'bmi calculator kg',
    'bmi calculator pounds',
    'healthy bmi',
    'normal bmi',
    'bmi range',
    'bmi categories',
    'underweight bmi',
    'overweight bmi',
    'obesity bmi',
    'bmi for men',
    'bmi for women',
    'bmi for kids',
    'bmi for teens',
    'bmi calculator age',
    'bmi calculator with age',
    'ideal bmi',
    'healthy weight calculator',
    'bmi prime calculator',
    'ponderal index calculator',
    'weight status calculator',
    'obesity calculator',
    'underweight calculator',
    'bmi weight chart',
    'bmi height weight chart',
    'calculate body mass index',
    'bmi calculation formula',
    'bmi metric formula',
    'bmi imperial formula',
    'kg m2 calculator',
    'body fat calculator',
    'weight loss bmi',
    'healthy weight range',
    'ideal weight calculator',
    'bmi percentile calculator',
    'bmi for athletes',
    'accurate bmi calculator',
    'bmi calculator with interpretation',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/bmi-calculator',
  },
  openGraph: {
    title: 'BMI Calculator - Calculate Your Body Mass Index',
    description: 'Free BMI calculator for adults and children. Calculate Body Mass Index using metric or imperial units with BMI classification and healthy weight ranges.',
    url: 'https://www.thetutorbridge.com/calculators/bmi-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'BMI Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BMI Calculator - Calculate Your Body Mass Index',
    description: 'Calculate your BMI with our free calculator. Get BMI classification, healthy weight range, and health insights for adults and children.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function BMICalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
