import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Mortgage Calculator - Free Home Loan Payment Calculator with Amortization Schedule | The Tutor Bridge',
  description: 'Free mortgage calculator to estimate monthly home loan payments. Calculate mortgage with taxes, insurance, PMI, and HOA fees. Get detailed amortization schedule and total interest breakdown.',
  keywords: [
    'mortgage calculator',
    'home loan calculator',
    'mortgage payment calculator',
    'house payment calculator',
    'mortgage calculator with taxes and insurance',
    'mortgage calculator with pmi',
    'home mortgage calculator',
    'monthly mortgage calculator',
    'mortgage amortization calculator',
    'loan payment calculator',
    'home loan payment calculator',
    'mortgage estimator',
    'house loan calculator',
    'calculate mortgage payment',
    'mortgage formula',
    'home affordability calculator',
    'mortgage with down payment',
    'property tax calculator',
    'mortgage interest calculator',
    'total mortgage cost',
    'mortgage calculator online',
    'free mortgage calculator',
    'mortgage calculator india',
    'home loan emi calculator',
    'mortgage rate calculator',
    'refinance calculator',
    'mortgage amortization schedule',
    'loan amortization calculator',
    'principal and interest calculator',
    'mortgage breakdown',
    'fixed rate mortgage calculator',
    'adjustable rate mortgage calculator',
    'arm calculator',
    'fha loan calculator',
    'va loan calculator',
    'conventional loan calculator',
    'jumbo loan calculator',
    'mortgage calculator with extra payments',
    'early payoff calculator',
    'mortgage prepayment calculator',
    'biweekly mortgage calculator',
    'mortgage comparison calculator',
    'home buying calculator',
    'closing costs calculator',
    'pmi calculator',
    'private mortgage insurance calculator',
    'hoa fee calculator',
    'homeowners insurance calculator',
    'property tax estimator',
    'mortgage affordability',
    'how much house can i afford',
    'mortgage qualification calculator',
    'debt to income ratio calculator',
    'mortgage budget calculator',
    'first time home buyer calculator',
    'mortgage calculator with escrow',
    'total interest paid calculator',
    'mortgage payoff calculator',
    'loan term calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/mortgage-calculator',
  },
  openGraph: {
    title: 'Mortgage Calculator - Calculate Home Loan Payments with Amortization',
    description: 'Free mortgage calculator with taxes, insurance, PMI, and HOA fees. Get monthly payment estimates and detailed amortization schedule.',
    url: 'https://www.thetutorbridge.com/calculators/mortgage-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Mortgage Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Mortgage Calculator - Calculate Home Loan Payments',
    description: 'Calculate monthly mortgage payments with taxes, insurance, and fees. Get detailed amortization schedule and interest breakdown.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MortgageCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
