import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'High School GPA Calculator - Weighted & Unweighted GPA with Honor Classes | The Tutor Bridge',
  description: 'Free high school GPA calculator for weighted and unweighted GPA with AP, IB, and honors classes. Calculate semester and cumulative GPA on 4.0 and 5.0 scales with comprehensive grading examples and class rank estimation.',
  keywords: [
    'high school gpa calculator',
    'gpa calculator high school',
    'weighted gpa calculator',
    'unweighted gpa calculator',
    'calculate high school gpa',
    'how to calculate gpa in high school',
    'high school grade calculator',
    'weighted vs unweighted gpa',
    'ap gpa calculator',
    'honors gpa calculator',
    'ib gpa calculator',
    'advanced placement gpa',
    'high school cumulative gpa',
    'high school semester gpa',
    'gpa calculator 4.0 scale',
    'gpa calculator 5.0 scale',
    'weighted gpa 5.0 scale',
    'calculate weighted gpa',
    'calculate unweighted gpa',
    'high school transcript calculator',
    'freshman gpa calculator',
    'sophomore gpa calculator',
    'junior gpa calculator',
    'senior gpa calculator',
    'college prep gpa calculator',
    'honors classes gpa',
    'ap classes gpa',
    'ib classes gpa',
    'dual enrollment gpa',
    'high school gpa for college',
    'college admissions gpa',
    'gpa requirements for college',
    'calculate class rank',
    'high school class rank calculator',
    'percentile gpa calculator',
    'free gpa calculator',
    'online gpa calculator',
    'high school grade point average',
    'how to calculate weighted gpa',
    'weighted gpa formula',
    'unweighted gpa formula',
    'gpa scale high school',
    'letter grade to gpa',
    'grade point calculator',
    'high school academic gpa',
    'core gpa calculator',
    'college prep courses gpa',
    'improve high school gpa',
    'raise gpa high school',
    'gpa tracker high school',
    'high school gpa planning',
    'target gpa calculator',
    'scholarship gpa requirements',
    'ncaa gpa calculator',
    'athletic eligibility gpa',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/high-school-gpa-calculator',
  },
  openGraph: {
    title: 'High School GPA Calculator - Weighted & Unweighted GPA with AP/IB/Honors',
    description: 'Calculate your high school GPA with weighted and unweighted scales. Support for AP, IB, honors classes on 4.0 and 5.0 scales with comprehensive examples.',
    url: 'https://thetutorbridge.com/calculators/high-school-gpa-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'High School GPA Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'High School GPA Calculator - Weighted & Unweighted GPA',
    description: 'Calculate weighted and unweighted high school GPA with AP, IB, and honors classes. Free calculator with comprehensive examples.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function HighSchoolGPACalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
