'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Home, Binary } from 'lucide-react';
import { Navigation } from '@/components/navigation';
import { Footer } from '@/components/footer';
export default function DecimalBinaryConverterPage() {
  const [decimal, setDecimal] = useState('');
  const [binary, setBinary] = useState('');
  const toBinary = () => setBinary(parseInt(decimal).toString(2));
  const toDecimal = () => setDecimal(parseInt(binary, 2).toString());
  return (<div className="flex flex-col min-h-screen"><Navigation /><div className="bg-gray-50 py-4 px-6"><div className="container mx-auto max-w-7xl"><nav className="flex items-center space-x-2 text-sm"><Link href="/" className="text-[#1A3D7C] hover:text-[#2BAE66] flex items-center"><Home className="w-4 h-4 mr-1" />Home</Link><span className="text-gray-400">/</span><Link href="/tools" className="text-[#1A3D7C] hover:text-[#2BAE66]">Tools</Link><span className="text-gray-400">/</span><span className="text-gray-600">Decimal to Binary Converter</span></nav></div></div><div className="flex-1 bg-gradient-to-br from-blue-50 via-white to-purple-50 py-12 px-4"><div className="max-w-4xl mx-auto"><div className="text-center mb-8"><div className="flex items-center justify-center mb-4"><Binary className="w-12 h-12 mr-3 text-[#2BAE66]" /><h1 className="text-4xl md:text-5xl font-bold text-gray-900">Decimal to Binary Converter</h1></div><p className="text-xl text-gray-600">Convert decimal to binary</p></div><div className="bg-white rounded-2xl shadow-xl p-8"><div className="space-y-6"><div><label className="block text-lg font-semibold text-gray-900 mb-3">Decimal</label><input type="text" value={decimal} onChange={(e) => setDecimal(e.target.value)} placeholder="123" className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:border-[#2BAE66] focus:outline-none text-gray-900 font-mono text-lg" /></div><div className="flex gap-4"><button onClick={toBinary} className="flex-1 px-8 py-4 bg-gradient-to-r from-[#1A3D7C] to-[#2BAE66] text-white rounded-lg font-bold text-lg hover:from-[#153162] hover:to-[#229554] transition-all shadow-lg">To Binary</button><button onClick={toDecimal} className="flex-1 px-8 py-4 bg-gradient-to-r from-[#2BAE66] to-[#1A3D7C] text-white rounded-lg font-bold text-lg hover:from-[#229554] hover:to-[#153162] transition-all shadow-lg">To Decimal</button></div><div><label className="block text-lg font-semibold text-gray-900 mb-3">Binary</label><input type="text" value={binary} onChange={(e) => setBinary(e.target.value)} placeholder="1111011" className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:border-[#2BAE66] focus:outline-none text-gray-900 font-mono text-lg" /></div></div></div></div></div><Footer /></div>);
}
