import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Grade Calculator - Calculate Your Final Grade & Course Grade | The Tutor Bridge',
  description: 'Free grade calculator to calculate your final grade, current grade, and needed scores. Weighted grades calculator with assignments, tests, quizzes, and exams. Find out what grade you need on your final exam to pass or get desired grade.',
  keywords: [
    'grade calculator',
    'final grade calculator',
    'calculate my grade',
    'course grade calculator',
    'class grade calculator',
    'weighted grade calculator',
    'test grade calculator',
    'exam grade calculator',
    'what grade do i need',
    'final exam grade calculator',
    'grade needed calculator',
    'calculate final grade',
    'current grade calculator',
    'semester grade calculator',
    'assignment grade calculator',
    'weighted average grade',
    'grade percentage calculator',
    'calculate course grade',
    'grade weight calculator',
    'student grade calculator',
    'academic grade calculator',
    'class average calculator',
    'grade points calculator',
    'calculate needed grade',
    'required grade calculator',
    'passing grade calculator',
    'what do i need on final',
    'grade forecasting',
    'grade prediction calculator',
    'weighted category grades',
    'assignment weight calculator',
    'test weight percentage',
    'quiz grade calculator',
    'homework grade calculator',
    'project grade calculator',
    'midterm grade calculator',
    'calculate letter grade',
    'percentage to letter grade',
    'grade breakdown calculator',
    'category weight calculator',
    'course weight calculator',
    'multiple assignment grades',
    'grade average calculator',
    'cumulative grade calculator',
    'overall grade calculator',
    'total grade calculator',
    'grade computation',
    'academic performance calculator',
    'student performance tracker',
    'grade tracking tool',
    'education grade calculator',
    'school grade calculator',
    'college grade calculator',
    'university grade calculator',
    'high school grade calculator',
    'grade analysis tool',
    'grade planning calculator',
    'grade improvement calculator',
    'grade scenario calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/grade-calculator',
  },
  openGraph: {
    title: 'Grade Calculator - Calculate Final Grade & Course Grade',
    description: 'Free weighted grade calculator to find your final grade, current grade, and required scores. Calculate what you need on finals to pass or achieve your target grade.',
    url: 'https://thetutorbridge.com/calculators/grade-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Grade Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Grade Calculator - Calculate Final Grade & Course Grade',
    description: 'Calculate your final grade, current grade, and what you need to score on finals. Free weighted grade calculator for students.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function GradeCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
