import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Middle School GPA Calculator - Calculate Your Junior High GPA | The Tutor Bridge',
  description: 'Free middle school GPA calculator to calculate your grades for 6th, 7th, and 8th grade. Track your junior high GPA on 4.0 scale, understand letter grades, prepare for high school, and improve academic performance.',
  keywords: [
    'middle school gpa calculator',
    'junior high gpa calculator',
    'middle school grade calculator',
    '6th grade gpa calculator',
    '7th grade gpa calculator',
    '8th grade gpa calculator',
    'junior high grade calculator',
    'middle school grades',
    'middle school academic calculator',
    'calculate middle school gpa',
    'middle school gpa 4.0 scale',
    'junior high gpa scale',
    'middle school grade point average',
    'middle school transcript calculator',
    'middle school report card gpa',
    'calculate junior high grades',
    'middle school semester gpa',
    'middle school cumulative gpa',
    'middle school student calculator',
    'junior high student grades',
    'middle school academic performance',
    'middle school grade tracker',
    'prepare for high school gpa',
    'middle school to high school transition',
    'junior high academic planner',
    'middle school honor roll calculator',
    'middle school academic standing',
    'middle school grade management',
    'junior high grade tracking',
    'middle school study planner',
    'calculate middle school average',
    'middle school letter grades',
    'middle school percentage to gpa',
    'middle school grading scale',
    'middle school gpa converter',
    'junior high grade converter',
    'middle school academic achievement',
    'middle school class rank',
    'junior high class standing',
    'middle school grade improvement',
    'middle school academic goals',
    'junior high academic success',
    'middle school transcript gpa',
    'middle school grade report',
    'calculate 6th grade gpa',
    'calculate 7th grade gpa',
    'calculate 8th grade gpa',
    'middle school education calculator',
    'junior high education tool',
    'middle school parent tool',
    'middle school teacher calculator',
    'middle school counselor resource',
    'middle school academic advisor tool',
    'middle school performance tracker',
    'junior high performance calculator',
    'middle school grade analyzer',
    'middle school academic monitoring',
    'middle school progress tracker',
    'junior high progress calculator',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://thetutorbridge.com/calculators/middle-school-gpa-calculator',
  },
  openGraph: {
    title: 'Middle School GPA Calculator - Calculate Junior High GPA',
    description: 'Free GPA calculator for middle school students (6th, 7th, 8th grade). Track your junior high grades, calculate GPA on 4.0 scale, and prepare for high school.',
    url: 'https://thetutorbridge.com/calculators/middle-school-gpa-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Middle School GPA Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Middle School GPA Calculator - Calculate Junior High GPA',
    description: 'Calculate your middle school GPA for 6th, 7th, and 8th grade. Track grades, understand the 4.0 scale, and prepare for high school.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MiddleSchoolGPACalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
