import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Semester Grade Calculator - Calculate Weighted Semester Grades with Quarters & Finals | The Tutor Bridge',
  description: 'Free semester grade calculator with step-by-step solutions. Calculate your semester grade using quarterly grades and final exam scores with customizable weights. Perfect for high school and college students.',
  keywords: [
    'semester grade calculator',
    'semester calculator',
    'calculate semester grade',
    'weighted semester grade calculator',
    'quarter grade calculator',
    'final exam grade calculator',
    'how to calculate semester grade',
    'semester average calculator',
    'free semester grade calculator',
    'online semester grade calculator',
    'semester grade calculator with weights',
    'semester grade formula',
    'quarterly grade calculator',
    'semester gpa calculator',
    'college semester grade calculator',
    'high school semester grade calculator',
    'semester grade calculation',
    'weighted grade calculator semester',
    'calculate final semester grade',
    'semester grade percentage calculator',
    'trimester grade calculator',
    'marking period grade calculator',
    'grading period calculator',
    'semester weighted average calculator',
    'calculate semester average',
    'semester report card calculator',
    'final grade calculator semester',
    'end of semester grade calculator',
    'semester course grade calculator',
    'semester class grade calculator',
    'quarter and final exam calculator',
    'weighted quarter grades calculator',
    'q1 q2 final exam calculator',
    'semester grading calculator',
    'calculate semester percentage',
    'semester grade point calculator',
    'weighted semester average',
    'calculate semester score',
    'semester mark calculator',
    'semester evaluation calculator',
    'academic semester calculator',
    'student semester grade calculator',
    'teacher semester grade calculator',
    'semester assessment calculator',
    'calculate semester performance',
    'semester progress calculator',
    'weighted grading calculator',
    'quarter weights calculator',
    'exam weight calculator',
    'grade weighting calculator semester',
    'calculate weighted semester grade',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/semester-grade-calculator',
  },
  openGraph: {
    title: 'Semester Grade Calculator - Calculate Weighted Semester Grades',
    description: 'Free semester grade calculator with step-by-step solutions. Calculate semester grades using quarterly grades and final exam scores with customizable weights.',
    url: 'https://www.thetutorbridge.com/calculators/semester-grade-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Semester Grade Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Semester Grade Calculator - Calculate Weighted Semester Grades',
    description: 'Calculate your semester grade using quarterly grades and final exam scores. Free calculator with customizable weights and step-by-step solutions.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function SemesterGradeCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
