import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Marks Percentage Calculator - Calculate Percentage from Marks Obtained & Total Marks | The Tutor Bridge',
  description: 'Free marks percentage calculator with comprehensive formulas, examples, and grading systems. Calculate your exam percentage instantly from marks obtained and total marks with detailed step-by-step solutions.',
  keywords: [
    'marks percentage calculator',
    'calculate percentage from marks',
    'marks to percentage',
    'percentage calculator marks',
    'exam percentage calculator',
    'how to calculate percentage of marks',
    'percentage marks calculator',
    'marks percentage formula',
    'calculate marks percentage',
    'percentage of marks obtained',
    'total marks to percentage',
    'exam marks percentage',
    'marks obtained percentage',
    'percentage calculator for students',
    'student marks calculator',
    'academic percentage calculator',
    'score percentage calculator',
    'test percentage calculator',
    'grade percentage calculator',
    'marks percentage conversion',
    'percentage from total marks',
    'calculate exam percentage',
    'marks percentage formula calculator',
    'percentage calculation from marks',
    'how to find percentage of marks',
    'marks scored percentage',
    'percentage calculator for exams',
    'calculate percentage marks obtained',
    'percentage of marks formula',
    'marks to percent converter',
    'exam score percentage',
    'test score percentage calculator',
    'marks percentage online',
    'free marks percentage calculator',
    'percentage marks online calculator',
    'calculate percentage of total marks',
    'percentage calculator with marks',
    'subject wise percentage calculator',
    'multiple subject percentage',
    'semester percentage calculator',
    'term marks percentage',
    'class test percentage',
    'annual exam percentage',
    'board exam percentage calculator',
    'school marks percentage',
    'college marks percentage',
    'university marks percentage',
    'cbse marks percentage',
    'icse marks percentage',
    'state board percentage calculator',
    'marks percentage with grade',
    'percentage and grade calculator',
    'marks percentage interpretation',
    'percentage calculation method',
    'marks percentage examples',
    'how percentage is calculated',
    'percentage formula for students',
    'academic performance percentage',
    'marks percentage chart',
    'percentage grading system',
    'marks to percentage table',
    'percentage calculation examples',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/marks-percentage-calculator',
  },
  openGraph: {
    title: 'Marks Percentage Calculator - Calculate Exam Percentage Instantly',
    description: 'Calculate percentage from marks obtained and total marks with comprehensive formulas and examples. Free marks percentage calculator for students.',
    url: 'https://thetutorbridge.com/calculators/marks-percentage-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Marks Percentage Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Marks Percentage Calculator - Free Student Tool',
    description: 'Calculate percentage from marks instantly with formulas and examples. Perfect for students and educators.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function MarksPercentageCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
