import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Percentage Calculator - Free % Calculator with Quick Solutions | The Tutor Bridge',
  description: 'Free percentage calculator with 3 quick solutions. Calculate what is X% of Y, X is what % of Y, and X is Y% of what. Perfect for students, business, and everyday calculations with step-by-step solutions.',
  keywords: [
    'percentage calculator',
    'percent calculator',
    'calculate percentage',
    'percentage calculation',
    'percent calculation',
    'how to calculate percentage',
    'percentage formula',
    'percentage calculator online',
    'free percentage calculator',
    'percentage solver',
    'what is percentage of',
    'what percent of',
    'percent of what',
    'percentage increase calculator',
    'percentage decrease calculator',
    'percentage difference calculator',
    'calculate percent',
    'find percentage',
    'percentage math',
    'percentage tool',
    'quick percentage calculator',
    'simple percentage calculator',
    'percentage calculator with steps',
    'percentage calculator free',
    'online percent calculator',
    'calculate % of number',
    'find percent of number',
    'what is x percent of y',
    'x is what percent of y',
    'x is y percent of what',
    'percentage word problems',
    'percentage examples',
    'percentage help',
    'business percentage calculator',
    'student percentage calculator',
    'math percentage calculator',
    'percentage calculator for students',
    'percentage calculator for business',
    'educational percentage calculator',
    'percentage problem solver',
    'percentage equation solver',
    'percentage conversion calculator',
    'convert to percentage',
    'percentage to decimal',
    'decimal to percentage',
    'fraction to percentage',
    'percentage of total',
    'percentage calculator step by step',
    'how to find percentage',
    'percentage tricks',
    'percentage shortcuts',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/percentage-calculator',
  },
  openGraph: {
    title: 'Percentage Calculator - Free % Calculator with Quick Solutions',
    description: 'Free percentage calculator with 3 quick solutions. Calculate percentages instantly with step-by-step explanations. Perfect for students and business.',
    url: 'https://www.thetutorbridge.com/calculators/percentage-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Percentage Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Percentage Calculator - Free Tool with Quick Solutions',
    description: 'Calculate percentages instantly with 3 quick solutions and step-by-step explanations.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function PercentageCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
