import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Random Number Generator - Free Random Number Picker Tool | The Tutor Bridge',
  description: 'Free random number generator to create random numbers between any range. Customize quantity, allow/disallow repeats, and sort options. Perfect for games, lottery, passwords, and random selection with instant results.',
  keywords: [
    'random number generator',
    'random number picker',
    'random generator',
    'number generator',
    'random number maker',
    'generate random numbers',
    'random number creator',
    'random integer generator',
    'random number tool',
    'free random number generator',
    'online random number generator',
    'random number between',
    'random number range',
    'random number selector',
    'pick random number',
    'random number picker wheel',
    'random number chooser',
    'true random number generator',
    'random digit generator',
    'multiple random numbers',
    'generate random numbers no repeats',
    'random number without repeats',
    'random number with duplicates',
    'sorted random numbers',
    'random list generator',
    'random numbers generator custom range',
    'random number generator 1-10',
    'random number generator 1-100',
    'random number generator 1-1000',
    'lottery number generator',
    'lucky number generator',
    'random number for games',
    'dice number generator',
    'random password numbers',
    'random pin generator',
    'random code generator',
    'raffle number generator',
    'random draw generator',
    'random selection tool',
    'number randomizer',
    'random integer picker',
    'how to generate random numbers',
    'random number formula',
    'cryptographic random numbers',
    'pseudo random numbers',
    'random number algorithms',
    'random sampling tool',
    'statistical random generator',
    'educational random tool',
    'math random numbers',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: '/calculators/random-number-generator',
  },
  openGraph: {
    title: 'Random Number Generator - Create Random Numbers Instantly',
    description: 'Free random number generator with custom range, quantity control, and sorting options. Generate random numbers for games, lottery, passwords, and more.',
    url: 'https://thetutorbridge.com/calculators/random-number-generator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Random Number Generator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Random Number Generator - Free Random Picker Tool',
    description: 'Generate random numbers with custom range and options. Perfect for lottery, games, sampling, and random selection.',
    images: ['https://thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RandomNumberGeneratorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
