import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Feet and Inches Calculator - Add, Subtract, Multiply & Divide | The Tutor Bridge',
  description: 'Free feet and inches calculator. Add, subtract, multiply, divide, or convert feet and inches with fractions and decimals. Step-by-step solutions with proper mathematical notation for construction, carpentry, and measurements.',
  keywords: [
    'feet and inches calculator',
    'feet inches calculator',
    'add feet and inches',
    'subtract feet and inches',
    'multiply feet and inches',
    'divide feet and inches',
    'feet and inches math',
    'feet inches addition calculator',
    'feet inches subtraction calculator',
    'construction calculator',
    'carpentry calculator',
    'measurement calculator',
    'imperial calculator',
    'feet to inches converter',
    'inches to feet converter',
    'feet and inches fractions',
    'feet and inches decimals',
    'building calculator',
    'contractor calculator',
    'woodworking calculator',
    'feet and inches operations',
    'imperial measurement calculator',
    'foot inch calculator',
    'feet inch math calculator',
    'construction math calculator',
    'free feet inches calculator',
    'online feet inches calculator',
    'feet and inches formula',
    'how to add feet and inches',
    'how to subtract feet and inches',
    'feet inches conversion',
    'imperial units calculator',
    'length calculator feet inches',
    'distance calculator feet inches',
    'dimension calculator',
    'feet inches mixed numbers',
    'feet inches fraction calculator',
    'architectural calculator',
    'engineering calculator feet inches',
    'building measurement calculator',
    'lumber calculator',
    'home improvement calculator',
    'renovation calculator',
    'flooring calculator feet inches',
    'room measurement calculator',
    'diy calculator feet inches',
    'trade calculator',
    'professional measurement calculator',
    'feet and inches arithmetic',
    'imperial measurement tool',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/feet-and-inches-calculator',
  },
  openGraph: {
    title: 'Feet and Inches Calculator - Add, Subtract, Multiply & Divide',
    description: 'Calculate with feet and inches using fractions and decimals. Perfect for construction, carpentry, and home improvement projects with step-by-step solutions.',
    url: 'https://www.thetutorbridge.com/calculators/feet-and-inches-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Feet and Inches Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Feet and Inches Calculator - Free Tool',
    description: 'Add, subtract, multiply, and divide feet and inches with fractions. Perfect for construction and carpentry.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function FeetAndInchesCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
