import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Factoring Calculator - Find All Factors and Factor Pairs | The Tutor Bridge',
  description: 'Free factoring calculator. Find all factors and factor pairs of any number with step-by-step solutions. Includes prime factorization, greatest common factor (GCF), and least common multiple (LCM) with proper mathematical notation.',
  keywords: [
    'factoring calculator',
    'factor calculator',
    'find factors',
    'factor pairs calculator',
    'factors of a number',
    'how to find factors',
    'free factoring calculator',
    'online factoring calculator',
    'factor finder',
    'factorization calculator',
    'factors and multiples',
    'prime factorization calculator',
    'gcf calculator',
    'greatest common factor',
    'lcm calculator',
    'least common multiple',
    'factor pairs',
    'divisors calculator',
    'number factors',
    'find all factors',
    'factor list',
    'complete factorization',
    'math factors calculator',
    'integer factors',
    'positive factors',
    'negative factors',
    'factor tree calculator',
    'prime factors',
    'composite factors',
    'factor decomposition',
    'divisibility calculator',
    'factors and divisors',
    'factoring tool',
    'factorization tool',
    'number theory calculator',
    'factor analysis',
    'factors solver',
    'find divisors',
    'factor pairs finder',
    'multiplication factors',
    'factor combinations',
    'factor breakdown',
    'number divisors',
    'factors list generator',
    'all factors calculator',
    'complete factors',
    'factor enumeration',
    'factoring numbers',
    'factor identification',
    'divisor finder',
  ],
  authors: [{ name: 'The Tutor Bridge' }],
  creator: 'The Tutor Bridge',
  publisher: 'The Tutor Bridge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://www.thetutorbridge.com/calculators/factoring-calculator',
  },
  openGraph: {
    title: 'Factoring Calculator - Find All Factors and Factor Pairs',
    description: 'Find all factors and factor pairs of any number with step-by-step solutions. Free tool for students and math learners.',
    url: 'https://www.thetutorbridge.com/calculators/factoring-calculator',
    siteName: 'The Tutor Bridge',
    type: 'website',
    images: [
      {
        url: 'https://www.thetutorbridge.com/og-calculator.png',
        width: 1200,
        height: 630,
        alt: 'Factoring Calculator - The Tutor Bridge',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Factoring Calculator - Free Tool',
    description: 'Find all factors and factor pairs with step-by-step solutions. Perfect for homework and learning.',
    images: ['https://www.thetutorbridge.com/og-calculator.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function FactoringCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
